name: side_hustle
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  shared_preferences: ^2.2.3
  logger: ^2.3.0
  path_provider: ^2.1.3
  validators: ^3.0.0
  latlong2: ^0.9.1
  intl:
  dropdown_button2: ^2.3.9
  material_symbols_icons: ^4.2768.0
  jwt_decoder: ^2.0.1
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.0.1
  image_picker: ^1.1.2
  http: ^1.2.1
  lottie: ^3.1.2
  phone_form_field: ^9.2.5
  animated_bottom_navigation_bar: ^1.3.3
  flutter_datetime_picker_plus: ^2.2.0
  otp_text_field: ^1.1.3
  animations: ^2.0.11
  flutter_onboarding_slider: ^1.0.11
  file_picker: ^8.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/json/categories.json
    - assets/json/governorates.json
    - assets/lottie/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
