name: dootify
description: "Free Your Time, Focus on Your Goals."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.2.1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_config: ^2.0.2
  get: ^4.6.6
  shared_preferences: ^2.2.3
  logger: ^2.3.0
  path_provider: ^2.1.3
  validators: ^3.0.0
  latlong2: ^0.9.1
  intl:
  dropdown_button2: ^2.3.9
  material_symbols_icons: ^4.2768.0
  jwt_decoder: ^2.0.1
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.0.1
  image_picker: ^1.1.2
  http: ^1.2.1
  lottie: ^3.1.2
  phone_form_field: ^9.2.5
  animated_bottom_navigation_bar: ^1.3.3
  flutter_datetime_picker_plus: ^2.2.0
  otp_text_field: ^1.1.3
  animations: ^2.0.11
  flutter_onboarding_slider: ^1.0.11
  file_picker: ^8.0.6
  drift: ^2.19.1+1
  connectivity_plus: ^6.0.3
  cached_network_image: ^3.3.1
  flutter_swipe_action_cell: ^3.1.3
  easy_image_viewer: ^1.5.1
  url_launcher: ^6.3.0
  currency_picker: ^2.0.21
  local_auth: ^2.2.0
  flutter_screen_lock: ^9.1.0
  flutter_map: ^7.0.2
  geolocator: ^12.0.0
  flutter_map_cancellable_tile_provider: ^3.0.0
  flutter_map_location_marker: ^9.0.0
  sqlite3_flutter_libs: ^0.5.24
  socket_io_client: ^2.0.3+1
  firebase_core: ^3.3.0
  firebase_messaging: ^15.0.4
  awesome_notifications: ^0.9.3+1
  card_loading: ^0.3.2
  flutter_libphonenumber: ^2.3.0
  flutter_rating_bar: ^4.0.1
  icons_launcher: ^2.1.7
  solid_bottom_sheet: ^0.1.13
  path:
  syncfusion_flutter_pdfviewer: ^27.1.52
  share_plus: ^10.1.1
  package_info_plus: ^8.1.1
  fl_chart: ^0.69.0
  universal_html: ^2.2.4
  webview_flutter: ^4.10.0

  image_picker_for_web: any
  video_player: ^2.9.2
  introduction_screen: ^3.1.14

dependency_overrides:
  animated_bottom_navigation_bar:
    path: lib/overrided_dependencies/animated_bottom_navigation_bar

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  drift_dev: ^2.9.0
  build_runner: ^2.4.5

icons_launcher:
  image_path: "assets/images/dootify-logo-icon-bg-white.png"
  platforms:
    android:
      enable: true
      image_path: "assets/images/dootify-logo-icon-bg-white.png"
      # adaptive_background_color: '#ffffff'
    ios:
      enable: true
      image_path: "assets/images/dootify-logo-icon-bg-white.png"
      dark_path: "assets/images/dootify-logo-icon-bg-black.png"
    web:
      enable: true
      image_path: "assets/images/dootify-logo-icon-bg-white.png"
      favicon_path: "assets/images/dootify-logo-icon-bg-white.png"

flutter:
  uses-material-design: true

  assets:
    - assets/json/
    - assets/lottie/
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
