import 'package:flutter/material.dart';

const Color kPrimaryColor = Color(0xFF36b292);
const Color kPrimaryColorWhiter = Color.fromARGB(255, 119, 180, 165);
Color kPrimaryOpacityColor = kPrimaryColor.withOpacity(0.5);
const LinearGradient bPrimaryColor = LinearGradient(colors: [Color.fromRGBO(29, 134, 100, 1), Color.fromRGBO(46, 165, 127, 1)]);
Color kPrimaryDark = Color.alphaBlend(kPrimaryColor, kNeutralColor.withOpacity(0.1));
const Color kSecondaryColor = Color(0xff232d37);
const MaterialColor kAccentColor = Colors.orange;
const Color kErrorColor = Color(0xFFE21200);
Color kErrorLightColor = Colors.red.shade600;
const Color kRatingColor = Color(0xFFFDCC0D);
Color kNeutralColor = Colors.grey.shade700;
Color kNeutralLightColor = Colors.grey.shade200;
Color kNeutralLightOpacityColor = kNeutralLightColor.withOpacity(0.7);
Color kNeutralOpacityColor = kNeutralColor.withOpacity(0.7);
const Color kBlackColor = Colors.black;
const Color kNeutralColor100 = Colors.white;
const Color kConfirmedColor = Color(0xFF34A853);
const Color kSelectedDarkColor = Color.fromARGB(255, 0, 114, 208);
const Color kSelectedColor = Color(0xff008BF9);
const Color kSelectedLightColor = Color.fromARGB(255, 49, 162, 255);
