import 'package:flutter/material.dart';

const Color kPrimaryColor = Color(0xFF0074FE);
const Color kPrimaryColorWhiter = Color.fromARGB(255, 119, 180, 165);
Color kPrimaryOpacityColor = kPrimaryColor.withOpacity(0.5);
const LinearGradient bPrimaryColor = LinearGradient(colors: [Color.fromRGBO(29, 134, 100, 1), Color.fromRGBO(46, 165, 127, 1)]);
Color kPrimaryDark = Color.alphaBlend(kPrimaryColor, kNeutralColor.withOpacity(0.1));
const Color kSecondaryColor = Color(0xff232d37);
const Color kAccentColor = Color(0xFFFF9931); // Colors.orange;
const Color kAccentDarkColor = Color.fromARGB(255, 106, 62, 19); // Colors.orange;
const Color kErrorColor = Color(0xFFE21200);
Color kErrorLightColor = Colors.red.shade600;
const Color kRatingColor = Color(0xFFFDCC0D);
const Color kNeutralColor = Color(0xFF252535); // Colors.grey.shade700;
const Color kNeutralLightColor = Color(0xFFF4F4F4); // Colors.grey.shade200;
Color kNeutralLightOpacityColor = kNeutralLightColor.withOpacity(0.7);
Color kNeutralOpacityColor = kNeutralColor.withOpacity(0.7);
const Color kBlackColor = Colors.black;
const Color kDisabledColor = Colors.grey;
const Color kNeutralColor100 = Colors.white;
const Color kConfirmedColor = Color(0xFF34A853);
const Color kSelectedDarkColor = Color.fromARGB(255, 0, 114, 208);
const Color kSelectedColor = Color(0xff008BF9);
const Color kSelectedLightColor = Color.fromARGB(255, 49, 162, 255);
