// config.js

const constantId = {
  Users: [
    {
      name: "Rafik",
      email: "rafik@gmail.com",
      password: "123",
      gender: "male",
      birthdate: "1992-09-23 ",
      phone_number: "+21653543541",
      isVerified: "none",
      isMailVerified: true,
      governorate_id: 17,
      role: "[admin]",
    },
  ],
  LanguageType: [
    {
      id: "1",
      language_code: "en",
      name: "English",
    },
    {
      id: "2",
      language_code: "de",
      name: "German",
    },
    {
      id: "3",
      language_code: "pl",
      name: "Polish",
    },
    {
      id: "4",
      language_code: "fr",
      name: "Fbabynch",
    },
    {
      id: "5",
      language_code: "es",
      name: "Spanish",
    },
    {
      id: "6",
      language_code: "it",
      name: "Italian",
    },
    {
      id: "7",
      language_code: "sv",
      name: "Swedish",
    },
    {
      id: "8",
      language_code: "da",
      name: "Danish",
    },
    {
      id: "9",
      language_code: "pt",
      name: "Portuguese",
    },
    {
      id: "10",
      language_code: "cs",
      name: "Czech",
    },
    {
      id: "11",
      language_code: "nl",
      name: "Dutch",
    },
    {
      id: "12",
      language_code: "fi",
      name: "Finnish",
    },
    {
      id: "13",
      language_code: "ru",
      name: "Russian",
    },
    {
      id: "14",
      language_code: "lv",
      name: "Latvian",
    },
    {
      id: "15",
      language_code: "lt",
      name: "Lithuanian",
    },
    {
      id: "16",
      language_code: "ee",
      name: "Estonian",
    },
    {
      id: "17",
      language_code: "sk",
      name: "Slovak",
    },
    {
      id: "18",
      language_code: "hu",
      name: "Hungarian",
    },
    {
      id: "19",
      language_code: "jp",
      name: "Japanese",
    },
    {
      id: "22",
      language_code: "bg",
      name: "Bulgarian",
    },
    {
      id: "23",
      language_code: "tk",
      name: "Turkish",
    },
    {
      id: "24",
      language_code: "gr",
      name: "Greek",
    },
    {
      id: "25",
      language_code: "ro",
      name: "Romanian",
    },
    {
      id: "26",
      language_code: "zh",
      name: "Chinese",
    },
    {
      id: "27",
      language_code: "ca",
      name: "Catalan",
    },
  ],
  categories: [
    {
      id: 1,
      name: "Household Services",
      icon: "0xea44",
      parentId: -1,
    },
    {
      id: 101,
      name: "Cleaning",
      icon: "0xf0ff",
      parentId: 1,
    },
    {
      id: 102,
      name: "Maintenance",
      icon: "0xf100",
      parentId: 1,
    },
    {
      id: 103,
      name: "Gardening",
      icon: "0xf8a9",
      parentId: 1,
    },
    {
      id: 104,
      name: "Moving & Relocation",
      icon: "0xe73e",
      parentId: 1,
    },
    {
      id: 2,
      name: "Personal Services",
      icon: "0xf100",
      parentId: -1,
    },
    {
      id: 201,
      name: "Errands",
      icon: "0xeb6f",
      parentId: 2,
    },
    {
      id: 202,
      name: "Health & Fitness",
      icon: "0xeb43",
      parentId: 2,
    },
    {
      id: 203,
      name: "Beauty & Wellness",
      icon: "0xef9d",
      parentId: 2,
    },
    {
      id: 3,
      name: "Childcare & Education",
      icon: "0xe80c",
      parentId: -1,
    },
    {
      id: 301,
      name: "Babysitting",
      icon: "0xeb41",
      parentId: 3,
    },
    {
      id: 302,
      name: "Tutoring",
      icon: "0xefec",
      parentId: 3,
    },
    {
      id: 303,
      name: "Special Needs Care",
      icon: "0xf1ab",
      parentId: 3,
    },
    {
      id: 4,
      name: "Pet Services",
      icon: "0xefb1",
      parentId: -1,
    },
    {
      id: 401,
      name: "Pet Sitting",
      icon: "0xe91d",
      parentId: 4,
    },
    {
      id: 402,
      name: "Dog Walking",
      icon: "0xf149",
      parentId: 4,
    },
    {
      id: 403,
      name: "Pet Grooming",
      icon: "0xe91d",
      parentId: 4,
    },
    {
      id: 404,
      name: "Veterinary Assistance",
      icon: "0xefb1",
      parentId: 4,
    },
    {
      id: 5,
      name: "Automotive Services",
      icon: "0xea56",
      parentId: -1,
    },
    {
      id: 501,
      name: "Car Washing & Detailing",
      icon: "0xe542",
      parentId: 5,
    },
    {
      id: 502,
      name: "Car Repair",
      icon: "0xea56",
      parentId: 5,
    },
    {
      id: 503,
      name: "Tire Services",
      icon: "0xebc8",
      parentId: 5,
    },
    {
      id: 504,
      name: "Towing Services",
      icon: "0xe71e",
      parentId: 5,
    },
    {
      id: 6,
      name: "Business Services",
      icon: "0xeb3f",
      parentId: -1,
    },
    {
      id: 601,
      name: "Administrative Support",
      icon: "0xf0e2",
      parentId: 6,
    },
    {
      id: 602,
      name: "Marketing & Sales",
      icon: "0xf17e",
      parentId: 6,
    },
    {
      id: 603,
      name: "Graphic Design",
      icon: "0xf10a",
      parentId: 6,
    },
    {
      id: 604,
      name: "Writing & Translation",
      icon: "0xeb02",
      parentId: 6,
    },
    {
      id: 7,
      name: "Event Services",
      icon: "0xe616",
      parentId: -1,
    },
    {
      id: 701,
      name: "Event Planning",
      icon: "0xe878",
      parentId: 7,
    },
    {
      id: 702,
      name: "Catering",
      icon: "0xf1f2",
      parentId: 7,
    },
    {
      id: 703,
      name: "Photography & Videography",
      icon: "0xe412",
      parentId: 7,
    },
    {
      id: 704,
      name: "Entertainment",
      icon: "0xf5ee",
      parentId: 7,
    },
    {
      id: 8,
      name: "Tech & Digital Services",
      icon: "0xe31e",
      parentId: -1,
    },
    {
      id: 801,
      name: "IT Support",
      icon: "0xf0e2",
      parentId: 8,
    },
    {
      id: 802,
      name: "Programming & Development",
      icon: "0xefb6",
      parentId: 8,
    },
    {
      id: 803,
      name: "Multimedia",
      icon: "0xf570",
      parentId: 8,
    },
    {
      id: 9,
      name: "Home Improvement",
      icon: "0xe9b2",
      parentId: -1,
    },
    {
      id: 901,
      name: "Construction",
      icon: "0xea3c",
      parentId: 9,
    },
    {
      id: 902,
      name: "Painting",
      icon: "0xe243",
      parentId: 9,
    },
    {
      id: 903,
      name: "Interior Design",
      icon: "0xf10a",
      parentId: 9,
    },
    {
      id: 10,
      name: "Miscellaneous Services",
      icon: "0xf535",
      parentId: -1,
    },
    {
      id: 1001,
      name: "Arts & Crafts",
      icon: "0xefcb",
      parentId: 10,
    },
    {
      id: 1002,
      name: "Music Lessons",
      icon: "0xe03d",
      parentId: 10,
    },
    {
      id: 1003,
      name: "Travel Assistance",
      icon: "0xef93",
      parentId: 10,
    },
  ],
  governorates: [
    {
      id: 1,
      name: "Ariana",
    },
    {
      id: 2,
      name: "Beja",
    },
    {
      id: 3,
      name: "Ben Arous",
    },
    {
      id: 4,
      name: "Bizerte",
    },
    {
      id: 5,
      name: "Gabes",
    },
    {
      id: 6,
      name: "Gafsa",
    },
    {
      id: 7,
      name: "Jendouba",
    },
    {
      id: 8,
      name: "Kairouan",
    },
    {
      id: 9,
      name: "Kasserine",
    },
    {
      id: 10,
      name: "Kebili",
    },
    {
      id: 11,
      name: "Kef",
    },
    {
      id: 12,
      name: "Mahdia",
    },
    {
      id: 13,
      name: "Manouba",
    },
    {
      id: 14,
      name: "Medenine",
    },
    {
      id: 15,
      name: "Monastir",
    },
    {
      id: 16,
      name: "Nabeul",
    },
    {
      id: 17,
      name: "Sfax",
    },
    {
      id: 18,
      name: "Sidi Bouzid",
    },
    {
      id: 19,
      name: "Siliana",
    },
    {
      id: 20,
      name: "Sousse",
    },
    {
      id: 21,
      name: "Tataouine",
    },
    {
      id: 22,
      name: "Tozeur",
    },
    {
      id: 23,
      name: "Tunis",
    },
    {
      id: 24,
      name: "Zaghouan",
    },
  ],
  tasks: [
    {
      id: 1,
      title: "House Cleaning",
      description: "Clean the entire house thoroughly.",
      price: 100.0,
      delivrables: "Clean and tidy house",
      owner_id: 1,
      governorate_id: 1,
      category_id: 101,
    },
    {
      id: 2,
      title: "Garden Maintenance",
      description: "Mow the lawn and trim the hedges.",
      price: 80.0,
      delivrables: "Well-maintained garden",
      owner_id: 1,
      governorate_id: 2,
      category_id: 103,
    },
    {
      id: 3,
      title: "Math Tutoring",
      description: "Help with high school math homework.",
      price: 50.0,
      delivrables: "Improved math skills",
      owner_id: 1,
      governorate_id: 3,
      category_id: 302,
    },
    {
      id: 4,
      title: "Dog Walking",
      description: "Walk my dog every morning.",
      price: 30.0,
      delivrables: "Walked and happy dog",
      owner_id: 1,
      governorate_id: 4,
      category_id: 402,
    },
    {
      id: 5,
      title: "Car Washing",
      description: "Wash and detail my car.",
      price: 70.0,
      delivrables: "Clean and shiny car",
      owner_id: 1,
      governorate_id: 5,
      category_id: 501,
    },
    {
      id: 6,
      title: "Logo Design",
      description: "Create a logo for my new business.",
      price: 200.0,
      delivrables: "Logo in various formats",
      owner_id: 1,
      governorate_id: 6,
      category_id: 603,
    },
    {
      id: 7,
      title: "Event Planning",
      description: "Organize a wedding ceremony.",
      price: 5000.0,
      delivrables: "Well-organized wedding",
      owner_id: 1,
      governorate_id: 7,
      category_id: 701,
    },
    {
      id: 8,
      title: "IT Support",
      description: "Fix my computer issues.",
      price: 150.0,
      delivrables: "Functioning computer",
      owner_id: 1,
      governorate_id: 8,
      category_id: 801,
    },
    {
      id: 9,
      title: "Home Painting",
      description: "Paint the living room walls.",
      price: 300.0,
      delivrables: "Freshly painted living room",
      owner_id: 1,
      governorate_id: 9,
      category_id: 902,
    },
    {
      id: 10,
      title: "Music Lessons",
      description: "Teach piano to beginners.",
      price: 40.0,
      delivrables: "Basic piano skills",
      owner_id: 1,
      governorate_id: 10,
      category_id: 1002,
    },
    {
      id: 11,
      title: "Fitness Training",
      description: "Personal fitness training sessions.",
      price: 60.0,
      delivrables: "Improved fitness",
      owner_id: 1,
      governorate_id: 11,
      category_id: 202,
    },
    {
      id: 12,
      title: "Special Needs Care",
      description: "Provide care for a child with special needs.",
      price: 100.0,
      delivrables: "Proper care and assistance",
      owner_id: 1,
      governorate_id: 12,
      category_id: 303,
    },
    {
      id: 13,
      title: "Administrative Support",
      description: "Help with office administration tasks.",
      price: 70.0,
      delivrables: "Completed administrative tasks",
      owner_id: 1,
      governorate_id: 13,
      category_id: 601,
    },
    {
      id: 14,
      title: "Photography",
      description: "Photograph my event.",
      price: 500.0,
      delivrables: "High-quality event photos",
      owner_id: 1,
      governorate_id: 14,
      category_id: 703,
    },
    {
      id: 15,
      title: "Veterinary Assistance",
      description: "Assist with veterinary procedures.",
      price: 120.0,
      delivrables: "Proper veterinary care",
      owner_id: 1,
      governorate_id: 15,
      category_id: 404,
    },
    {
      id: 16,
      title: "Errand Running",
      description: "Run various errands.",
      price: 50.0,
      delivrables: "Completed errands",
      owner_id: 1,
      governorate_id: 16,
      category_id: 201,
    },
    {
      id: 17,
      title: "Construction Work",
      description: "Assist with home construction.",
      price: 400.0,
      delivrables: "Constructed home section",
      owner_id: 1,
      governorate_id: 17,
      category_id: 901,
    },
    {
      id: 18,
      title: "Travel Assistance",
      description: "Help plan a vacation.",
      price: 150.0,
      delivrables: "Well-planned trip",
      owner_id: 1,
      governorate_id: 18,
      category_id: 1003,
    },
    {
      id: 19,
      title: "Car Repair",
      description: "Fix my car's engine issues.",
      price: 300.0,
      delivrables: "Fixed car engine",
      owner_id: 1,
      governorate_id: 19,
      category_id: 502,
    },
    {
      id: 20,
      title: "Interior Design",
      description: "Design my living room interior.",
      price: 500.0,
      delivrables: "Stylish living room",
      owner_id: 1,
      governorate_id: 20,
      category_id: 903,
    },
    {
      id: 21,
      title: "Babysitting",
      description: "Babysit my 2-year-old son.",
      price: 60.0,
      delivrables: "Safe and entertained child",
      owner_id: 1,
      governorate_id: 21,
      category_id: 301,
    },
    {
      id: 22,
      title: "Beauty Services",
      description: "Provide a manicure and pedicure.",
      price: 70.0,
      delivrables: "Well-groomed nails",
      owner_id: 1,
      governorate_id: 22,
      category_id: 203,
    },
    {
      id: 23,
      title: "Moving Assistance",
      description: "Help me move to a new apartment.",
      price: 200.0,
      delivrables: "Moved belongings",
      owner_id: 1,
      governorate_id: 23,
      category_id: 104,
    },
    {
      id: 24,
      title: "Marketing Support",
      description: "Assist with marketing my product.",
      price: 150.0,
      delivrables: "Effective marketing campaign",
      owner_id: 1,
      governorate_id: 24,
      category_id: 602,
    },
    {
      id: 25,
      title: "Pet Grooming",
      description: "Groom my dog.",
      price: 50.0,
      delivrables: "Well-groomed dog",
      owner_id: 1,
      governorate_id: 1,
      category_id: 403,
    },
    {
      id: 26,
      title: "Catering Services",
      description: "Cater food for a party.",
      price: 1000.0,
      delivrables: "Delicious and timely food",
      owner_id: 1,
      governorate_id: 2,
      category_id: 702,
    },
    {
      id: 27,
      title: "Tire Services",
      description: "Change car tires.",
      price: 100.0,
      delivrables: "Newly installed tires",
      owner_id: 1,
      governorate_id: 3,
      category_id: 503,
    },
    {
      id: 28,
      title: "Arts & Crafts",
      description: "Create custom art pieces.",
      price: 200.0,
      delivrables: "Unique art pieces",
      owner_id: 1,
      governorate_id: 4,
      category_id: 1001,
    },
    {
      id: 29,
      title: "Health Coaching",
      description: "Provide health coaching sessions.",
      price: 60.0,
      delivrables: "Improved health and fitness",
      owner_id: 1,
      governorate_id: 5,
      category_id: 202,
    },
    {
      id: 30,
      title: "Writing & Translation",
      description: "Translate documents to French.",
      price: 120.0,
      delivrables: "Translated documents",
      owner_id: 1,
      governorate_id: 6,
      category_id: 604,
    },
    {
      id: 31,
      title: "Special Needs Care",
      description: "Provide care for a child with special needs.",
      price: 100.0,
      delivrables: "Proper care and assistance",
      owner_id: 1,
      governorate_id: 7,
      category_id: 303,
    },
    {
      id: 32,
      title: "Event Entertainment",
      description: "Provide entertainment for an event.",
      price: 500.0,
      delivrables: "Entertained guests",
      owner_id: 1,
      governorate_id: 8,
      category_id: 704,
    },
    {
      id: 33,
      title: "Pet Sitting",
      description: "Take care of pets while the owner is away.",
      price: 40.0,
      delivrables: "Safe and happy pets",
      owner_id: 1,
      governorate_id: 9,
      category_id: 401,
    },
    {
      id: 34,
      title: "Home Maintenance",
      description: "Fix minor home issues.",
      price: 90.0,
      delivrables: "Repaired home",
      owner_id: 1,
      governorate_id: 10,
      category_id: 102,
    },
    {
      id: 35,
      title: "IT Support",
      description: "Fix my computer issues.",
      price: 150.0,
      delivrables: "Functioning computer",
      owner_id: 1,
      governorate_id: 11,
      category_id: 801,
    },
    {
      id: 36,
      title: "Dog Walking",
      description: "Walk my dog every morning.",
      price: 30.0,
      delivrables: "Walked and happy dog",
      owner_id: 1,
      governorate_id: 12,
      category_id: 402,
    },
    {
      id: 37,
      title: "Tutoring",
      description: "Help with high school math homework.",
      price: 50.0,
      delivrables: "Improved math skills",
      owner_id: 1,
      governorate_id: 13,
      category_id: 302,
    },
    {
      id: 38,
      title: "Marketing Support",
      description: "Assist with marketing my product.",
      price: 150.0,
      delivrables: "Effective marketing campaign",
      owner_id: 1,
      governorate_id: 14,
      category_id: 602,
    },
    {
      id: 39,
      title: "Babysitting",
      description: "Babysit my 2-year-old son.",
      price: 60.0,
      delivrables: "Safe and entertained child",
      owner_id: 1,
      governorate_id: 15,
      category_id: 301,
    },
    {
      id: 40,
      title: "Travel Assistance",
      description: "Help plan a vacation.",
      price: 150.0,
      delivrables: "Well-planned trip",
      owner_id: 1,
      governorate_id: 16,
      category_id: 1003,
    },
    {
      id: 41,
      title: "Car Repair",
      description: "Fix my car's engine issues.",
      price: 300.0,
      delivrables: "Fixed car engine",
      owner_id: 1,
      governorate_id: 17,
      category_id: 502,
    },
    {
      id: 42,
      title: "Graphic Design",
      description: "Design a flyer for my event.",
      price: 200.0,
      delivrables: "Event flyer",
      owner_id: 1,
      governorate_id: 18,
      category_id: 603,
    },
    {
      id: 43,
      title: "Gardening",
      description: "Mow the lawn and trim the hedges.",
      price: 80.0,
      delivrables: "Well-maintained garden",
      owner_id: 1,
      governorate_id: 19,
      category_id: 103,
    },
    {
      id: 44,
      title: "Fitness Training",
      description: "Personal fitness training sessions.",
      price: 60.0,
      delivrables: "Improved fitness",
      owner_id: 1,
      governorate_id: 20,
      category_id: 202,
    },
    {
      id: 45,
      title: "Car Washing",
      description: "Wash and detail my car.",
      price: 70.0,
      delivrables: "Clean and shiny car",
      owner_id: 1,
      governorate_id: 21,
      category_id: 501,
    },
    {
      id: 46,
      title: "Health Coaching",
      description: "Provide health coaching sessions.",
      price: 60.0,
      delivrables: "Improved health and fitness",
      owner_id: 1,
      governorate_id: 22,
      category_id: 202,
    },
    {
      id: 47,
      title: "Photography",
      description: "Photograph my event.",
      price: 500.0,
      delivrables: "High-quality event photos",
      owner_id: 1,
      governorate_id: 23,
      category_id: 703,
    },
    {
      id: 48,
      title: "Veterinary Assistance",
      description: "Assist with veterinary procedures.",
      price: 120.0,
      delivrables: "Proper veterinary care",
      owner_id: 1,
      governorate_id: 24,
      category_id: 404,
    },
    {
      id: 49,
      title: "Event Planning",
      description: "Organize a wedding ceremony.",
      price: 5000.0,
      delivrables: "Well-organized wedding",
      owner_id: 1,
      governorate_id: 1,
      category_id: 701,
    },
    {
      id: 50,
      title: "Music Lessons",
      description: "Teach piano to beginners.",
      price: 40.0,
      delivrables: "Basic piano skills",
      owner_id: 1,
      governorate_id: 2,
      category_id: 1002,
    },
    {
      id: 51,
      title: "Interior Design",
      description: "Design my living room interior.",
      price: 500.0,
      delivrables: "Stylish living room",
      owner_id: 1,
      governorate_id: 3,
      category_id: 903,
    },
    {
      id: 52,
      title: "House Cleaning",
      description: "Clean the entire house thoroughly.",
      price: 100.0,
      delivrables: "Clean and tidy house",
      owner_id: 1,
      governorate_id: 4,
      category_id: 101,
    },
    {
      id: 53,
      title: "IT Support",
      description: "Fix my computer issues.",
      price: 150.0,
      delivrables: "Functioning computer",
      owner_id: 1,
      governorate_id: 5,
      category_id: 801,
    },
    {
      id: 54,
      title: "Administrative Support",
      description: "Assist with administrative tasks.",
      price: 100.0,
      delivrables: "Completed administrative tasks",
      owner_id: 1,
      governorate_id: 6,
      category_id: 601,
    },
    {
      id: 55,
      title: "Event Catering",
      description: "Provide catering services for an event.",
      price: 1000.0,
      delivrables: "Delicious food for the event",
      owner_id: 1,
      governorate_id: 7,
      category_id: 702,
    },
    {
      id: 56,
      title: "Painting",
      description: "Paint the interior of a house.",
      price: 800.0,
      delivrables: "Freshly painted rooms",
      owner_id: 1,
      governorate_id: 8,
      category_id: 902,
    },
    {
      id: 57,
      title: "Pet Grooming",
      description: "Groom my dog.",
      price: 50.0,
      delivrables: "Well-groomed dog",
      owner_id: 1,
      governorate_id: 9,
      category_id: 403,
    },
    {
      id: 58,
      title: "Errands",
      description: "Run errands for a busy professional.",
      price: 30.0,
      delivrables: "Completed errands",
      owner_id: 1,
      governorate_id: 10,
      category_id: 201,
    },
    {
      id: 59,
      title: "Multimedia Services",
      description: "Create a promotional video.",
      price: 400.0,
      delivrables: "High-quality promotional video",
      owner_id: 1,
      governorate_id: 11,
      category_id: 803,
    },
    {
      id: 60,
      title: "Marketing & Sales",
      description: "Assist with sales strategies.",
      price: 150.0,
      delivrables: "Effective sales strategies",
      owner_id: 1,
      governorate_id: 12,
      category_id: 602,
    },
    {
      id: 61,
      title: "Moving & Relocation",
      description: "Help with moving to a new house.",
      price: 200.0,
      delivrables: "Assistance with moving",
      owner_id: 1,
      governorate_id: 13,
      category_id: 104,
    },
    {
      id: 62,
      title: "Pet Sitting",
      description: "Take care of pets while the owner is away.",
      price: 40.0,
      delivrables: "Safe and happy pets",
      owner_id: 1,
      governorate_id: 14,
      category_id: 401,
    },
    {
      id: 63,
      title: "Tech Support",
      description: "Fix my laptop issues.",
      price: 100.0,
      delivrables: "Fixed laptop",
      owner_id: 1,
      governorate_id: 15,
      category_id: 801,
    },
    {
      id: 64,
      title: "Graphic Design",
      description: "Design a logo for my business.",
      price: 250.0,
      delivrables: "Business logo",
      owner_id: 1,
      governorate_id: 16,
      category_id: 603,
    },
    {
      id: 65,
      title: "Household Maintenance",
      description: "Fix minor issues around the house.",
      price: 80.0,
      delivrables: "Repaired household items",
      owner_id: 1,
      governorate_id: 17,
      category_id: 102,
    },
    {
      id: 66,
      title: "Photography",
      description: "Photograph a wedding.",
      price: 1000.0,
      delivrables: "High-quality wedding photos",
      owner_id: 1,
      governorate_id: 18,
      category_id: 703,
    },
    {
      id: 67,
      title: "Health & Fitness",
      description: "Provide personal training sessions.",
      price: 60.0,
      delivrables: "Improved fitness",
      owner_id: 1,
      governorate_id: 19,
      category_id: 202,
    },
    {
      id: 68,
      title: "Car Washing",
      description: "Wash and detail my car.",
      price: 70.0,
      delivrables: "Clean and shiny car",
      owner_id: 1,
      governorate_id: 20,
      category_id: 501,
    },
    {
      id: 69,
      title: "Administrative Support",
      description: "Assist with office work.",
      price: 100.0,
      delivrables: "Completed office tasks",
      owner_id: 1,
      governorate_id: 21,
      category_id: 601,
    },
    {
      id: 70,
      title: "Painting",
      description: "Paint the exterior of a house.",
      price: 1000.0,
      delivrables: "Freshly painted exterior",
      owner_id: 1,
      governorate_id: 22,
      category_id: 902,
    },
    {
      id: 71,
      title: "Event Planning",
      description: "Plan a corporate event.",
      price: 3000.0,
      delivrables: "Well-organized event",
      owner_id: 1,
      governorate_id: 23,
      category_id: 701,
    },
    {
      id: 72,
      title: "Dog Walking",
      description: "Walk my dog every evening.",
      price: 30.0,
      delivrables: "Walked and happy dog",
      owner_id: 1,
      governorate_id: 24,
      category_id: 402,
    },
    {
      id: 73,
      title: "Construction",
      description: "Build a garden shed.",
      price: 2000.0,
      delivrables: "New garden shed",
      owner_id: 1,
      governorate_id: 1,
      category_id: 901,
    },
    {
      id: 74,
      title: "Pet Grooming",
      description: "Groom my cat.",
      price: 50.0,
      delivrables: "Well-groomed cat",
      owner_id: 1,
      governorate_id: 2,
      category_id: 403,
    },
    {
      id: 75,
      title: "Health Coaching",
      description: "Provide health coaching sessions.",
      price: 60.0,
      delivrables: "Improved health and fitness",
      owner_id: 1,
      governorate_id: 3,
      category_id: 202,
    },
    {
      id: 76,
      title: "Pet Sitting",
      description: "Take care of pets while the owner is away.",
      price: 40.0,
      delivrables: "Safe and happy pets",
      owner_id: 1,
      governorate_id: 4,
      category_id: 401,
    },
    {
      id: 77,
      title: "Tutoring",
      description: "Help with university-level physics.",
      price: 60.0,
      delivrables: "Improved physics understanding",
      owner_id: 1,
      governorate_id: 5,
      category_id: 302,
    },
    {
      id: 78,
      title: "Music Lessons",
      description: "Teach guitar to beginners.",
      price: 40.0,
      delivrables: "Basic guitar skills",
      owner_id: 1,
      governorate_id: 6,
      category_id: 1002,
    },
    {
      id: 79,
      title: "IT Support",
      description: "Fix my computer issues.",
      price: 150.0,
      delivrables: "Functioning computer",
      owner_id: 1,
      governorate_id: 7,
      category_id: 801,
    },
    {
      id: 80,
      title: "Event Photography",
      description: "Photograph a corporate event.",
      price: 800.0,
      delivrables: "High-quality event photos",
      owner_id: 1,
      governorate_id: 8,
      category_id: 703,
    },
    {
      id: 81,
      title: "Dog Walking",
      description: "Walk my dog in the morning.",
      price: 20.0,
      delivrables: "Walked and happy dog",
      owner_id: 1,
      governorate_id: 9,
      category_id: 402,
    },
    {
      id: 82,
      title: "Graphic Design",
      description: "Create promotional materials.",
      price: 300.0,
      delivrables: "Promotional materials",
      owner_id: 1,
      governorate_id: 10,
      category_id: 603,
    },
    {
      id: 83,
      title: "Car Repair",
      description: "Fix my car's engine issues.",
      price: 500.0,
      delivrables: "Repaired car engine",
      owner_id: 1,
      governorate_id: 11,
      category_id: 502,
    },
    {
      id: 84,
      title: "Special Needs Care",
      description: "Provide care for a special needs child.",
      price: 100.0,
      delivrables: "Cared for child",
      owner_id: 1,
      governorate_id: 12,
      category_id: 303,
    },
    {
      id: 85,
      title: "Travel Assistance",
      description: "Plan a trip to Europe.",
      price: 150.0,
      delivrables: "Well-planned trip itinerary",
      owner_id: 1,
      governorate_id: 13,
      category_id: 1003,
    },
    {
      id: 86,
      title: "Towing Services",
      description: "Tow my car to the mechanic.",
      price: 100.0,
      delivrables: "Car towed to mechanic",
      owner_id: 1,
      governorate_id: 14,
      category_id: 504,
    },
    {
      id: 87,
      title: "Beauty & Wellness",
      description: "Provide a full body massage.",
      price: 70.0,
      delivrables: "Relaxed client",
      owner_id: 1,
      governorate_id: 15,
      category_id: 203,
    },
    {
      id: 88,
      title: "Tutoring",
      description: "Help with high school math.",
      price: 50.0,
      delivrables: "Improved math skills",
      owner_id: 1,
      governorate_id: 16,
      category_id: 302,
    },
    {
      id: 89,
      title: "Gardening",
      description: "Maintain my garden.",
      price: 60.0,
      delivrables: "Well-maintained garden",
      owner_id: 1,
      governorate_id: 17,
      category_id: 103,
    },
    {
      id: 90,
      title: "Veterinary Assistance",
      description: "Assist with my pet's vet visit.",
      price: 40.0,
      delivrables: "Pet cared for at vet",
      owner_id: 1,
      governorate_id: 18,
      category_id: 404,
    },
    {
      id: 91,
      title: "Writing & Translation",
      description: "Translate a document to French.",
      price: 200.0,
      delivrables: "Translated document",
      owner_id: 1,
      governorate_id: 19,
      category_id: 604,
    },
    {
      id: 92,
      title: "Painting",
      description: "Paint a mural on a wall.",
      price: 500.0,
      delivrables: "Finished mural",
      owner_id: 1,
      governorate_id: 20,
      category_id: 902,
    },
    {
      id: 93,
      title: "IT Support",
      description: "Set up a new computer system.",
      price: 200.0,
      delivrables: "Set up computer system",
      owner_id: 1,
      governorate_id: 21,
      category_id: 801,
    },
    {
      id: 94,
      title: "Catering",
      description: "Provide food for a small event.",
      price: 800.0,
      delivrables: "Event catering",
      owner_id: 1,
      governorate_id: 22,
      category_id: 702,
    },
    {
      id: 95,
      title: "Pet Grooming",
      description: "Groom my dog.",
      price: 50.0,
      delivrables: "Well-groomed dog",
      owner_id: 1,
      governorate_id: 23,
      category_id: 403,
    },
    {
      id: 96,
      title: "Health & Fitness",
      description: "Provide a personal training session.",
      price: 60.0,
      delivrables: "Improved fitness",
      owner_id: 1,
      governorate_id: 24,
      category_id: 202,
    },
    {
      id: 97,
      title: "Arts & Crafts",
      description: "Teach a pottery class.",
      price: 50.0,
      delivrables: "Basic pottery skills",
      owner_id: 1,
      governorate_id: 1,
      category_id: 1001,
    },
    {
      id: 98,
      title: "Car Repair",
      description: "Fix my car's brakes.",
      price: 400.0,
      delivrables: "Repaired brakes",
      owner_id: 1,
      governorate_id: 2,
      category_id: 502,
    },
    {
      id: 99,
      title: "Babysitting",
      description: "Babysit my children for an evening.",
      price: 60.0,
      delivrables: "Cared for children",
      owner_id: 1,
      governorate_id: 3,
      category_id: 301,
    },
    {
      id: 100,
      title: "Interior Design",
      description: "Redesign my living room.",
      price: 700.0,
      delivrables: "New living room design",
      owner_id: 1,
      governorate_id: 4,
      category_id: 903,
    },
  ],
};

const prefixPatterns = [
  // Europe
  { prefix: "+44", pattern: /^\+44\d{10}$/ }, // United Kingdom
  { prefix: "+33", pattern: /^\+33\d{9}$/ }, // France
  { prefix: "+49", pattern: /^\+49\d{10}$/ }, // Germany
  { prefix: "+39", pattern: /^\+39\d{10}$/ }, // Italy
  { prefix: "+31", pattern: /^\+31\d{9,10}$/ }, // Netherlands
  { prefix: "+34", pattern: /^\+34\d{9}$/ }, // Spain
  { prefix: "+41", pattern: /^\+41\d{9}$/ }, // Switzerland
  { prefix: "+46", pattern: /^\+46\d{9}$/ }, // Sweden
  { prefix: "+358", pattern: /^\+358\d{9}$/ }, // Finland
  { prefix: "+47", pattern: /^\+47\d{8}$/ }, // Norway

  // North Africa
  { prefix: "+213", pattern: /^\+213\d{9}$/ }, // Algeria
  { prefix: "+20", pattern: /^\+20\d{10}$/ }, // Egypt
  { prefix: "+212", pattern: /^\+212\d{9}$/ }, // Morocco
  { prefix: "+216", pattern: /^\+216\d{8}$/ }, // Tunisia
  { prefix: "+218", pattern: /^\+218\d{9}$/ }, // Libya
  { prefix: "+235", pattern: /^\+235\d{8}$/ }, // Chad
  { prefix: "+249", pattern: /^\+249\d{9}$/ }, // Sudan
  { prefix: "+212", pattern: /^\+212\d{9}$/ }, // Western Sahara
  { prefix: "+213", pattern: /^\+213\d{9}$/ }, // Canary Islands
  { prefix: "+20", pattern: /^\+20\d{10}$/ }, // Canary Islands

  // USA
  { prefix: "+1", pattern: /^\+1\d{10}$/ }, // United States
  { prefix: "+1", pattern: /^\+1\d{10}$/ }, // Canada
  { prefix: "+52", pattern: /^\+52\d{10}$/ }, // Mexico
  { prefix: "+52", pattern: /^\+52\d{10}$/ }, // Belize
  { prefix: "+52", pattern: /^\+52\d{10}$/ }, // Guatemala
  { prefix: "+52", pattern: /^\+52\d{10}$/ }, // Honduras
  { prefix: "+52", pattern: /^\+52\d{10}$/ }, // El Salvador
  { prefix: "+52", pattern: /^\+52\d{10}$/ }, // Nicaragua
  { prefix: "+52", pattern: /^\+52\d{10}$/ }, // Costa Rica
  { prefix: "+52", pattern: /^\+52\d{10}$/ }, // Panama
];

module.exports = {
  constantId,
  prefixPatterns,
};
