// config.js

const constantId = {
  Users: [
    {
      id: 1,
      name: "Rafik Admin",
      email: "rafik.admin@gmail.com",
      password: "123",
      gender: "male",
      birthdate: "1992-09-23",
      phone_number: "+21653543541",
      isVerified: "verified",
      isMailVerified: true,
      governorate_id: 17,
      role: "admin",
    },
    {
      id: 2,
      name: "Rafik Seeker",
      email: "rafik.seeker@gmail.com",
      password: "123",
      gender: "male",
      birthdate: "1992-09-23",
      phone_number: "+21622222222",
      isVerified: "verified",
      isMailVerified: true,
      governorate_id: 17,
      role: "seeker",
    },
    {
      id: 3,
      name: "Rafik Provider",
      email: "rafik.provider@gmail.com",
      password: "123",
      gender: "male",
      birthdate: "1992-09-23",
      phone_number: "+21623232323",
      isVerified: "none",
      isMailVerified: true,
      governorate_id: 17,
      role: "provider",
    },
  ],
  LanguageType: [
    {
      id: "1",
      language_code: "en",
      name: "English",
    },
    {
      id: "2",
      language_code: "de",
      name: "German",
    },
    {
      id: "3",
      language_code: "pl",
      name: "Polish",
    },
    {
      id: "4",
      language_code: "fr",
      name: "Fbabynch",
    },
    {
      id: "5",
      language_code: "es",
      name: "Spanish",
    },
    {
      id: "6",
      language_code: "it",
      name: "Italian",
    },
    {
      id: "7",
      language_code: "sv",
      name: "Swedish",
    },
    {
      id: "8",
      language_code: "da",
      name: "Danish",
    },
    {
      id: "9",
      language_code: "pt",
      name: "Portuguese",
    },
    {
      id: "10",
      language_code: "cs",
      name: "Czech",
    },
    {
      id: "11",
      language_code: "nl",
      name: "Dutch",
    },
    {
      id: "12",
      language_code: "fi",
      name: "Finnish",
    },
    {
      id: "13",
      language_code: "ru",
      name: "Russian",
    },
    {
      id: "14",
      language_code: "lv",
      name: "Latvian",
    },
    {
      id: "15",
      language_code: "lt",
      name: "Lithuanian",
    },
    {
      id: "16",
      language_code: "ee",
      name: "Estonian",
    },
    {
      id: "17",
      language_code: "sk",
      name: "Slovak",
    },
    {
      id: "18",
      language_code: "hu",
      name: "Hungarian",
    },
    {
      id: "19",
      language_code: "jp",
      name: "Japanese",
    },
    {
      id: "22",
      language_code: "bg",
      name: "Bulgarian",
    },
    {
      id: "23",
      language_code: "tk",
      name: "Turkish",
    },
    {
      id: "24",
      language_code: "gr",
      name: "Greek",
    },
    {
      id: "25",
      language_code: "ro",
      name: "Romanian",
    },
    {
      id: "26",
      language_code: "zh",
      name: "Chinese",
    },
    {
      id: "27",
      language_code: "ca",
      name: "Catalan",
    },
  ],
  categories: [
    {
      id: 1,
      name: "Household Services",
      icon: "0xea44",
      parentId: -1,
    },
    {
      id: 101,
      name: "Cleaning",
      icon: "0xf0ff",
      parentId: 1,
    },
    {
      id: 102,
      name: "Maintenance",
      icon: "0xf100",
      parentId: 1,
    },
    {
      id: 103,
      name: "Gardening",
      icon: "0xf8a9",
      parentId: 1,
    },
    {
      id: 104,
      name: "Moving & Relocation",
      icon: "0xe73e",
      parentId: 1,
    },
    {
      id: 2,
      name: "Personal Services",
      icon: "0xf100",
      parentId: -1,
    },
    {
      id: 201,
      name: "Errands",
      icon: "0xeb6f",
      parentId: 2,
    },
    {
      id: 202,
      name: "Health & Fitness",
      icon: "0xeb43",
      parentId: 2,
    },
    {
      id: 203,
      name: "Beauty & Wellness",
      icon: "0xef9d",
      parentId: 2,
    },
    {
      id: 3,
      name: "Childcare & Education",
      icon: "0xe80c",
      parentId: -1,
    },
    {
      id: 301,
      name: "Babysitting",
      icon: "0xeb41",
      parentId: 3,
    },
    {
      id: 302,
      name: "Tutoring",
      icon: "0xefec",
      parentId: 3,
    },
    {
      id: 303,
      name: "Special Needs Care",
      icon: "0xf1ab",
      parentId: 3,
    },
    {
      id: 4,
      name: "Pet Services",
      icon: "0xefb1",
      parentId: -1,
    },
    {
      id: 401,
      name: "Pet Sitting",
      icon: "0xe91d",
      parentId: 4,
    },
    {
      id: 402,
      name: "Dog Walking",
      icon: "0xf149",
      parentId: 4,
    },
    {
      id: 403,
      name: "Pet Grooming",
      icon: "0xe91d",
      parentId: 4,
    },
    {
      id: 404,
      name: "Veterinary Assistance",
      icon: "0xefb1",
      parentId: 4,
    },
    {
      id: 5,
      name: "Automotive Services",
      icon: "0xea56",
      parentId: -1,
    },
    {
      id: 501,
      name: "Car Washing & Detailing",
      icon: "0xe542",
      parentId: 5,
    },
    {
      id: 502,
      name: "Car Repair",
      icon: "0xea56",
      parentId: 5,
    },
    {
      id: 503,
      name: "Tire Services",
      icon: "0xebc8",
      parentId: 5,
    },
    {
      id: 504,
      name: "Towing Services",
      icon: "0xe71e",
      parentId: 5,
    },
    {
      id: 6,
      name: "Business Services",
      icon: "0xeb3f",
      parentId: -1,
    },
    {
      id: 601,
      name: "Administrative Support",
      icon: "0xf0e2",
      parentId: 6,
    },
    {
      id: 602,
      name: "Marketing & Sales",
      icon: "0xf17e",
      parentId: 6,
    },
    {
      id: 603,
      name: "Graphic Design",
      icon: "0xf10a",
      parentId: 6,
    },
    {
      id: 604,
      name: "Writing & Translation",
      icon: "0xeb02",
      parentId: 6,
    },
    {
      id: 7,
      name: "Event Services",
      icon: "0xe616",
      parentId: -1,
    },
    {
      id: 701,
      name: "Event Planning",
      icon: "0xe878",
      parentId: 7,
    },
    {
      id: 702,
      name: "Catering",
      icon: "0xf1f2",
      parentId: 7,
    },
    {
      id: 703,
      name: "Photography & Videography",
      icon: "0xe412",
      parentId: 7,
    },
    {
      id: 704,
      name: "Entertainment",
      icon: "0xf5ee",
      parentId: 7,
    },
    {
      id: 8,
      name: "Tech & Digital Services",
      icon: "0xe31e",
      parentId: -1,
    },
    {
      id: 801,
      name: "IT Support",
      icon: "0xf0e2",
      parentId: 8,
    },
    {
      id: 802,
      name: "Programming & Development",
      icon: "0xefb6",
      parentId: 8,
    },
    {
      id: 803,
      name: "Multimedia",
      icon: "0xf570",
      parentId: 8,
    },
    {
      id: 9,
      name: "Home Improvement",
      icon: "0xe9b2",
      parentId: -1,
    },
    {
      id: 901,
      name: "Construction",
      icon: "0xea3c",
      parentId: 9,
    },
    {
      id: 902,
      name: "Painting",
      icon: "0xe243",
      parentId: 9,
    },
    {
      id: 903,
      name: "Interior Design",
      icon: "0xf10a",
      parentId: 9,
    },
    {
      id: 10,
      name: "Miscellaneous Services",
      icon: "0xf535",
      parentId: -1,
    },
    {
      id: 1001,
      name: "Arts & Crafts",
      icon: "0xefcb",
      parentId: 10,
    },
    {
      id: 1002,
      name: "Music Lessons",
      icon: "0xe03d",
      parentId: 10,
    },
    {
      id: 1003,
      name: "Travel Assistance",
      icon: "0xef93",
      parentId: 10,
    },
  ],
  governorates: [
    {
      id: 1,
      name: "All Tunisia",
    },
    {
      id: 2,
      name: "Ariana",
    },
    {
      id: 3,
      name: "Beja",
    },
    {
      id: 4,
      name: "Ben Arous",
    },
    {
      id: 5,
      name: "Bizerte",
    },
    {
      id: 6,
      name: "Gabes",
    },
    {
      id: 7,
      name: "Gafsa",
    },
    {
      id: 8,
      name: "Jendouba",
    },
    {
      id: 9,
      name: "Kairouan",
    },
    {
      id: 10,
      name: "Kasserine",
    },
    {
      id: 11,
      name: "Kebili",
    },
    {
      id: 12,
      name: "Kef",
    },
    {
      id: 13,
      name: "Mahdia",
    },
    {
      id: 14,
      name: "Manouba",
    },
    {
      id: 15,
      name: "Medenine",
    },
    {
      id: 16,
      name: "Monastir",
    },
    {
      id: 17,
      name: "Nabeul",
    },
    {
      id: 18,
      name: "Sfax",
    },
    {
      id: 19,
      name: "Sidi Bouzid",
    },
    {
      id: 20,
      name: "Siliana",
    },
    {
      id: 21,
      name: "Sousse",
    },
    {
      id: 22,
      name: "Tataouine",
    },
    {
      id: 23,
      name: "Tozeur",
    },
    {
      id: 24,
      name: "Tunis",
    },
    {
      id: 25,
      name: "Zaghouan",
    },
  ],
  tasks: [
    {
      id: 1,
      title: "House Cleaning",
      description: "Clean the entire house thoroughly.",
      price: 100.0,
      delivrables: "Clean and tidy house",
      owner_id: 1,
      governorate_id: 1,
      category_id: 101,
    },
    {
      id: 2,
      title: "Garden Maintenance",
      description: "Mow the lawn and trim the hedges.",
      price: 80.0,
      delivrables: "Well-maintained garden",
      owner_id: 1,
      governorate_id: 2,
      category_id: 103,
    },
    {
      id: 3,
      title: "Math Tutoring",
      description: "Help with high school math homework.",
      price: 50.0,
      delivrables: "Improved math skills",
      owner_id: 1,
      governorate_id: 3,
      category_id: 302,
    },
    {
      id: 4,
      title: "Dog Walking",
      description: "Walk my dog every morning.",
      price: 30.0,
      delivrables: "Walked and happy dog",
      owner_id: 1,
      governorate_id: 4,
      category_id: 402,
    },
    {
      id: 5,
      title: "Car Washing",
      description: "Wash and detail my car.",
      price: 70.0,
      delivrables: "Clean and shiny car",
      owner_id: 1,
      governorate_id: 5,
      category_id: 501,
    },
    {
      id: 6,
      title: "Logo Design",
      description: "Create a logo for my new business.",
      price: 200.0,
      delivrables: "Logo in various formats",
      owner_id: 1,
      governorate_id: 6,
      category_id: 603,
    },
    {
      id: 7,
      title: "Event Planning",
      description: "Organize a wedding ceremony.",
      price: 5000.0,
      delivrables: "Well-organized wedding",
      owner_id: 1,
      governorate_id: 7,
      category_id: 701,
    },
    {
      id: 8,
      title: "IT Support",
      description: "Fix my computer issues.",
      price: 150.0,
      delivrables: "Functioning computer",
      owner_id: 1,
      governorate_id: 8,
      category_id: 801,
    },
    {
      id: 9,
      title: "Home Painting",
      description: "Paint the living room walls.",
      price: 300.0,
      delivrables: "Freshly painted living room",
      owner_id: 1,
      governorate_id: 9,
      category_id: 902,
    },
    {
      id: 10,
      title: "Music Lessons",
      description: "Teach piano to beginners.",
      price: 40.0,
      delivrables: "Basic piano skills",
      owner_id: 1,
      governorate_id: 10,
      category_id: 1002,
    },
    {
      id: 11,
      title: "Fitness Training",
      description: "Personal fitness training sessions.",
      price: 60.0,
      delivrables: "Improved fitness",
      owner_id: 1,
      governorate_id: 11,
      category_id: 202,
    },
    {
      id: 12,
      title: "Special Needs Care",
      description: "Provide care for a child with special needs.",
      price: 100.0,
      delivrables: "Proper care and assistance",
      owner_id: 1,
      governorate_id: 12,
      category_id: 303,
    },
    {
      id: 13,
      title: "Administrative Support",
      description: "Help with office administration tasks.",
      price: 70.0,
      delivrables: "Completed administrative tasks",
      owner_id: 1,
      governorate_id: 13,
      category_id: 601,
    },
    {
      id: 14,
      title: "Photography",
      description: "Photograph my event.",
      price: 500.0,
      delivrables: "High-quality event photos",
      owner_id: 1,
      governorate_id: 14,
      category_id: 703,
    },
    {
      id: 15,
      title: "Veterinary Assistance",
      description: "Assist with veterinary procedures.",
      price: 120.0,
      delivrables: "Proper veterinary care",
      owner_id: 1,
      governorate_id: 15,
      category_id: 404,
    },
    {
      id: 16,
      title: "Errand Running",
      description: "Run various errands.",
      price: 50.0,
      delivrables: "Completed errands",
      owner_id: 1,
      governorate_id: 16,
      category_id: 201,
    },
    {
      id: 17,
      title: "Construction Work",
      description: "Assist with home construction.",
      price: 400.0,
      delivrables: "Constructed home section",
      owner_id: 1,
      governorate_id: 17,
      category_id: 901,
    },
    {
      id: 18,
      title: "Travel Assistance",
      description: "Help plan a vacation.",
      price: 150.0,
      delivrables: "Well-planned trip",
      owner_id: 1,
      governorate_id: 18,
      category_id: 1003,
    },
    {
      id: 19,
      title: "Car Repair",
      description: "Fix my car's engine issues.",
      price: 300.0,
      delivrables: "Fixed car engine",
      owner_id: 1,
      governorate_id: 19,
      category_id: 502,
    },
    {
      id: 20,
      title: "Interior Design",
      description: "Design my living room interior.",
      price: 500.0,
      delivrables: "Stylish living room",
      owner_id: 1,
      governorate_id: 20,
      category_id: 903,
    },
    {
      id: 21,
      title: "Babysitting",
      description: "Babysit my 2-year-old son.",
      price: 60.0,
      delivrables: "Safe and entertained child",
      owner_id: 1,
      governorate_id: 21,
      category_id: 301,
    },
    {
      id: 22,
      title: "Beauty Services",
      description: "Provide a manicure and pedicure.",
      price: 70.0,
      delivrables: "Well-groomed nails",
      owner_id: 1,
      governorate_id: 22,
      category_id: 203,
    },
    {
      id: 23,
      title: "Moving Assistance",
      description: "Help me move to a new apartment.",
      price: 200.0,
      delivrables: "Moved belongings",
      owner_id: 1,
      governorate_id: 23,
      category_id: 104,
    },
    {
      id: 24,
      title: "Marketing Support",
      description: "Assist with marketing my product.",
      price: 150.0,
      delivrables: "Effective marketing campaign",
      owner_id: 1,
      governorate_id: 24,
      category_id: 602,
    },
    {
      id: 25,
      title: "Pet Grooming",
      description: "Groom my dog.",
      price: 50.0,
      delivrables: "Well-groomed dog",
      owner_id: 1,
      governorate_id: 1,
      category_id: 403,
    },
    {
      id: 26,
      title: "Catering Services",
      description: "Cater food for a party.",
      price: 1000.0,
      delivrables: "Delicious and timely food",
      owner_id: 1,
      governorate_id: 2,
      category_id: 702,
    },
    {
      id: 27,
      title: "Tire Services",
      description: "Change car tires.",
      price: 100.0,
      delivrables: "Newly installed tires",
      owner_id: 1,
      governorate_id: 3,
      category_id: 503,
    },
    {
      id: 28,
      title: "Arts & Crafts",
      description: "Create custom art pieces.",
      price: 200.0,
      delivrables: "Unique art pieces",
      owner_id: 1,
      governorate_id: 4,
      category_id: 1001,
    },
    {
      id: 29,
      title: "Health Coaching",
      description: "Provide health coaching sessions.",
      price: 60.0,
      delivrables: "Improved health and fitness",
      owner_id: 1,
      governorate_id: 5,
      category_id: 202,
    },
    {
      id: 30,
      title: "Writing & Translation",
      description: "Translate documents to French.",
      price: 120.0,
      delivrables: "Translated documents",
      owner_id: 1,
      governorate_id: 6,
      category_id: 604,
    },
    {
      id: 31,
      title: "Special Needs Care",
      description: "Provide care for a child with special needs.",
      price: 100.0,
      delivrables: "Proper care and assistance",
      owner_id: 1,
      governorate_id: 7,
      category_id: 303,
    },
    {
      id: 32,
      title: "Event Entertainment",
      description: "Provide entertainment for an event.",
      price: 500.0,
      delivrables: "Entertained guests",
      owner_id: 1,
      governorate_id: 8,
      category_id: 704,
    },
    {
      id: 33,
      title: "Pet Sitting",
      description: "Take care of pets while the owner is away.",
      price: 40.0,
      delivrables: "Safe and happy pets",
      owner_id: 1,
      governorate_id: 9,
      category_id: 401,
    },
    {
      id: 34,
      title: "Home Maintenance",
      description: "Fix minor home issues.",
      price: 90.0,
      delivrables: "Repaired home",
      owner_id: 1,
      governorate_id: 10,
      category_id: 102,
    },
    {
      id: 35,
      title: "IT Support",
      description: "Fix my computer issues.",
      price: 150.0,
      delivrables: "Functioning computer",
      owner_id: 1,
      governorate_id: 11,
      category_id: 801,
    },
    {
      id: 36,
      title: "Dog Walking",
      description: "Walk my dog every morning.",
      price: 30.0,
      delivrables: "Walked and happy dog",
      owner_id: 1,
      governorate_id: 12,
      category_id: 402,
    },
    {
      id: 37,
      title: "Tutoring",
      description: "Help with high school math homework.",
      price: 50.0,
      delivrables: "Improved math skills",
      owner_id: 1,
      governorate_id: 13,
      category_id: 302,
    },
    {
      id: 38,
      title: "Marketing Support",
      description: "Assist with marketing my product.",
      price: 150.0,
      delivrables: "Effective marketing campaign",
      owner_id: 1,
      governorate_id: 14,
      category_id: 602,
    },
    {
      id: 39,
      title: "Babysitting",
      description: "Babysit my 2-year-old son.",
      price: 60.0,
      delivrables: "Safe and entertained child",
      owner_id: 1,
      governorate_id: 15,
      category_id: 301,
    },
    {
      id: 40,
      title: "Travel Assistance",
      description: "Help plan a vacation.",
      price: 150.0,
      delivrables: "Well-planned trip",
      owner_id: 1,
      governorate_id: 16,
      category_id: 1003,
    },
    {
      id: 41,
      title: "Car Repair",
      description: "Fix my car's engine issues.",
      price: 300.0,
      delivrables: "Fixed car engine",
      owner_id: 1,
      governorate_id: 17,
      category_id: 502,
    },
    {
      id: 42,
      title: "Graphic Design",
      description: "Design a flyer for my event.",
      price: 200.0,
      delivrables: "Event flyer",
      owner_id: 1,
      governorate_id: 18,
      category_id: 603,
    },
    {
      id: 43,
      title: "Gardening",
      description: "Mow the lawn and trim the hedges.",
      price: 80.0,
      delivrables: "Well-maintained garden",
      owner_id: 1,
      governorate_id: 19,
      category_id: 103,
    },
    {
      id: 44,
      title: "Fitness Training",
      description: "Personal fitness training sessions.",
      price: 60.0,
      delivrables: "Improved fitness",
      owner_id: 1,
      governorate_id: 20,
      category_id: 202,
    },
    {
      id: 45,
      title: "Car Washing",
      description: "Wash and detail my car.",
      price: 70.0,
      delivrables: "Clean and shiny car",
      owner_id: 1,
      governorate_id: 21,
      category_id: 501,
    },
    {
      id: 46,
      title: "Health Coaching",
      description: "Provide health coaching sessions.",
      price: 60.0,
      delivrables: "Improved health and fitness",
      owner_id: 1,
      governorate_id: 22,
      category_id: 202,
    },
    {
      id: 47,
      title: "Photography",
      description: "Photograph my event.",
      price: 500.0,
      delivrables: "High-quality event photos",
      owner_id: 1,
      governorate_id: 23,
      category_id: 703,
    },
    {
      id: 48,
      title: "Veterinary Assistance",
      description: "Assist with veterinary procedures.",
      price: 120.0,
      delivrables: "Proper veterinary care",
      owner_id: 1,
      governorate_id: 24,
      category_id: 404,
    },
    {
      id: 49,
      title: "Event Planning",
      description: "Organize a wedding ceremony.",
      price: 5000.0,
      delivrables: "Well-organized wedding",
      owner_id: 1,
      governorate_id: 1,
      category_id: 701,
    },
    {
      id: 50,
      title: "Music Lessons",
      description: "Teach piano to beginners.",
      price: 40.0,
      delivrables: "Basic piano skills",
      owner_id: 1,
      governorate_id: 2,
      category_id: 1002,
    },
    {
      id: 51,
      title: "Interior Design",
      description: "Design my living room interior.",
      price: 500.0,
      delivrables: "Stylish living room",
      owner_id: 1,
      governorate_id: 3,
      category_id: 903,
    },
    {
      id: 52,
      title: "House Cleaning",
      description: "Clean the entire house thoroughly.",
      price: 100.0,
      delivrables: "Clean and tidy house",
      owner_id: 1,
      governorate_id: 4,
      category_id: 101,
    },
    {
      id: 53,
      title: "IT Support",
      description: "Fix my computer issues.",
      price: 150.0,
      delivrables: "Functioning computer",
      owner_id: 1,
      governorate_id: 5,
      category_id: 801,
    },
    {
      id: 54,
      title: "Administrative Support",
      description: "Assist with administrative tasks.",
      price: 100.0,
      delivrables: "Completed administrative tasks",
      owner_id: 1,
      governorate_id: 6,
      category_id: 601,
    },
    {
      id: 55,
      title: "Event Catering",
      description: "Provide catering services for an event.",
      price: 1000.0,
      delivrables: "Delicious food for the event",
      owner_id: 1,
      governorate_id: 7,
      category_id: 702,
    },
    {
      id: 56,
      title: "Painting",
      description: "Paint the interior of a house.",
      price: 800.0,
      delivrables: "Freshly painted rooms",
      owner_id: 1,
      governorate_id: 8,
      category_id: 902,
    },
    {
      id: 57,
      title: "Pet Grooming",
      description: "Groom my dog.",
      price: 50.0,
      delivrables: "Well-groomed dog",
      owner_id: 1,
      governorate_id: 9,
      category_id: 403,
    },
    {
      id: 58,
      title: "Errands",
      description: "Run errands for a busy professional.",
      price: 30.0,
      delivrables: "Completed errands",
      owner_id: 1,
      governorate_id: 10,
      category_id: 201,
    },
    {
      id: 59,
      title: "Multimedia Services",
      description: "Create a promotional video.",
      price: 400.0,
      delivrables: "High-quality promotional video",
      owner_id: 1,
      governorate_id: 11,
      category_id: 803,
    },
    {
      id: 60,
      title: "Marketing & Sales",
      description: "Assist with sales strategies.",
      price: 150.0,
      delivrables: "Effective sales strategies",
      owner_id: 1,
      governorate_id: 12,
      category_id: 602,
    },
    {
      id: 61,
      title: "Moving & Relocation",
      description: "Help with moving to a new house.",
      price: 200.0,
      delivrables: "Assistance with moving",
      owner_id: 1,
      governorate_id: 13,
      category_id: 104,
    },
    {
      id: 62,
      title: "Pet Sitting",
      description: "Take care of pets while the owner is away.",
      price: 40.0,
      delivrables: "Safe and happy pets",
      owner_id: 1,
      governorate_id: 14,
      category_id: 401,
    },
    {
      id: 63,
      title: "Tech Support",
      description: "Fix my laptop issues.",
      price: 100.0,
      delivrables: "Fixed laptop",
      owner_id: 1,
      governorate_id: 15,
      category_id: 801,
    },
    {
      id: 64,
      title: "Graphic Design",
      description: "Design a logo for my business.",
      price: 250.0,
      delivrables: "Business logo",
      owner_id: 1,
      governorate_id: 16,
      category_id: 603,
    },
    {
      id: 65,
      title: "Household Maintenance",
      description: "Fix minor issues around the house.",
      price: 80.0,
      delivrables: "Repaired household items",
      owner_id: 1,
      governorate_id: 17,
      category_id: 102,
    },
    {
      id: 66,
      title: "Photography",
      description: "Photograph a wedding.",
      price: 1000.0,
      delivrables: "High-quality wedding photos",
      owner_id: 1,
      governorate_id: 18,
      category_id: 703,
    },
    {
      id: 67,
      title: "Health & Fitness",
      description: "Provide personal training sessions.",
      price: 60.0,
      delivrables: "Improved fitness",
      owner_id: 1,
      governorate_id: 19,
      category_id: 202,
    },
    {
      id: 68,
      title: "Car Washing",
      description: "Wash and detail my car.",
      price: 70.0,
      delivrables: "Clean and shiny car",
      owner_id: 1,
      governorate_id: 20,
      category_id: 501,
    },
    {
      id: 69,
      title: "Administrative Support",
      description: "Assist with office work.",
      price: 100.0,
      delivrables: "Completed office tasks",
      owner_id: 1,
      governorate_id: 21,
      category_id: 601,
    },
    {
      id: 70,
      title: "Painting",
      description: "Paint the exterior of a house.",
      price: 1000.0,
      delivrables: "Freshly painted exterior",
      owner_id: 1,
      governorate_id: 22,
      category_id: 902,
    },
    {
      id: 71,
      title: "Event Planning",
      description: "Plan a corporate event.",
      price: 3000.0,
      delivrables: "Well-organized event",
      owner_id: 1,
      governorate_id: 23,
      category_id: 701,
    },
    {
      id: 72,
      title: "Dog Walking",
      description: "Walk my dog every evening.",
      price: 30.0,
      delivrables: "Walked and happy dog",
      owner_id: 1,
      governorate_id: 24,
      category_id: 402,
    },
    {
      id: 73,
      title: "Construction",
      description: "Build a garden shed.",
      price: 2000.0,
      delivrables: "New garden shed",
      owner_id: 1,
      governorate_id: 1,
      category_id: 901,
    },
    {
      id: 74,
      title: "Pet Grooming",
      description: "Groom my cat.",
      price: 50.0,
      delivrables: "Well-groomed cat",
      owner_id: 1,
      governorate_id: 2,
      category_id: 403,
    },
    {
      id: 75,
      title: "Health Coaching",
      description: "Provide health coaching sessions.",
      price: 60.0,
      delivrables: "Improved health and fitness",
      owner_id: 1,
      governorate_id: 3,
      category_id: 202,
    },
    {
      id: 76,
      title: "Pet Sitting",
      description: "Take care of pets while the owner is away.",
      price: 40.0,
      delivrables: "Safe and happy pets",
      owner_id: 1,
      governorate_id: 4,
      category_id: 401,
    },
    {
      id: 77,
      title: "Tutoring",
      description: "Help with university-level physics.",
      price: 60.0,
      delivrables: "Improved physics understanding",
      owner_id: 1,
      governorate_id: 5,
      category_id: 302,
    },
    {
      id: 78,
      title: "Music Lessons",
      description: "Teach guitar to beginners.",
      price: 40.0,
      delivrables: "Basic guitar skills",
      owner_id: 1,
      governorate_id: 6,
      category_id: 1002,
    },
    {
      id: 79,
      title: "IT Support",
      description: "Fix my computer issues.",
      price: 150.0,
      delivrables: "Functioning computer",
      owner_id: 1,
      governorate_id: 7,
      category_id: 801,
    },
    {
      id: 80,
      title: "Event Photography",
      description: "Photograph a corporate event.",
      price: 800.0,
      delivrables: "High-quality event photos",
      owner_id: 1,
      governorate_id: 8,
      category_id: 703,
    },
    {
      id: 81,
      title: "Dog Walking",
      description: "Walk my dog in the morning.",
      price: 20.0,
      delivrables: "Walked and happy dog",
      owner_id: 1,
      governorate_id: 9,
      category_id: 402,
    },
    {
      id: 82,
      title: "Graphic Design",
      description: "Create promotional materials.",
      price: 300.0,
      delivrables: "Promotional materials",
      owner_id: 1,
      governorate_id: 10,
      category_id: 603,
    },
    {
      id: 83,
      title: "Car Repair",
      description: "Fix my car's engine issues.",
      price: 500.0,
      delivrables: "Repaired car engine",
      owner_id: 1,
      governorate_id: 11,
      category_id: 502,
    },
    {
      id: 84,
      title: "Special Needs Care",
      description: "Provide care for a special needs child.",
      price: 100.0,
      delivrables: "Cared for child",
      owner_id: 1,
      governorate_id: 12,
      category_id: 303,
    },
    {
      id: 85,
      title: "Travel Assistance",
      description: "Plan a trip to Europe.",
      price: 150.0,
      delivrables: "Well-planned trip itinerary",
      owner_id: 1,
      governorate_id: 13,
      category_id: 1003,
    },
    {
      id: 86,
      title: "Towing Services",
      description: "Tow my car to the mechanic.",
      price: 100.0,
      delivrables: "Car towed to mechanic",
      owner_id: 1,
      governorate_id: 14,
      category_id: 504,
    },
    {
      id: 87,
      title: "Beauty & Wellness",
      description: "Provide a full body massage.",
      price: 70.0,
      delivrables: "Relaxed client",
      owner_id: 1,
      governorate_id: 15,
      category_id: 203,
    },
    {
      id: 88,
      title: "Tutoring",
      description: "Help with high school math.",
      price: 50.0,
      delivrables: "Improved math skills",
      owner_id: 1,
      governorate_id: 16,
      category_id: 302,
    },
    {
      id: 89,
      title: "Gardening",
      description: "Maintain my garden.",
      price: 60.0,
      delivrables: "Well-maintained garden",
      owner_id: 1,
      governorate_id: 17,
      category_id: 103,
    },
    {
      id: 90,
      title: "Veterinary Assistance",
      description: "Assist with my pet's vet visit.",
      price: 40.0,
      delivrables: "Pet cared for at vet",
      owner_id: 1,
      governorate_id: 18,
      category_id: 404,
    },
    {
      id: 91,
      title: "Writing & Translation",
      description: "Translate a document to French.",
      price: 200.0,
      delivrables: "Translated document",
      owner_id: 1,
      governorate_id: 19,
      category_id: 604,
    },
    {
      id: 92,
      title: "Painting",
      description: "Paint a mural on a wall.",
      price: 500.0,
      delivrables: "Finished mural",
      owner_id: 1,
      governorate_id: 20,
      category_id: 902,
    },
    {
      id: 93,
      title: "IT Support",
      description: "Set up a new computer system.",
      price: 200.0,
      delivrables: "Set up computer system",
      owner_id: 1,
      governorate_id: 21,
      category_id: 801,
    },
    {
      id: 94,
      title: "Catering",
      description: "Provide food for a small event.",
      price: 800.0,
      delivrables: "Event catering",
      owner_id: 1,
      governorate_id: 22,
      category_id: 702,
    },
    {
      id: 95,
      title: "Pet Grooming",
      description: "Groom my dog.",
      price: 50.0,
      delivrables: "Well-groomed dog",
      owner_id: 1,
      governorate_id: 23,
      category_id: 403,
    },
    {
      id: 96,
      title: "Health & Fitness",
      description: "Provide a personal training session.",
      price: 60.0,
      delivrables: "Improved fitness",
      owner_id: 1,
      governorate_id: 24,
      category_id: 202,
    },
    {
      id: 97,
      title: "Arts & Crafts",
      description: "Teach a pottery class.",
      price: 50.0,
      delivrables: "Basic pottery skills",
      owner_id: 1,
      governorate_id: 1,
      category_id: 1001,
    },
    {
      id: 98,
      title: "Car Repair",
      description: "Fix my car's brakes.",
      price: 400.0,
      delivrables: "Repaired brakes",
      owner_id: 1,
      governorate_id: 2,
      category_id: 502,
    },
    {
      id: 99,
      title: "Babysitting",
      description: "Babysit my children for an evening.",
      price: 60.0,
      delivrables: "Cared for children",
      owner_id: 1,
      governorate_id: 3,
      category_id: 301,
    },
    {
      id: 100,
      title: "Interior Design",
      description: "Redesign my living room.",
      price: 700.0,
      delivrables: "New living room design",
      owner_id: 1,
      governorate_id: 4,
      category_id: 903,
    },
  ],
  stores: [
    {
      id: 1,
      name: "TechFixers",
      coordinates: "40.712776,-74.005974",
      description: "Expert tech repair services.",
      owner_id: 1,
      governorate_id: 1,
    },
    {
      id: 2,
      name: "Beauty Bliss",
      coordinates: "34.052235,-118.243683",
      description: "Luxurious beauty and spa services.",
      owner_id: 1,
      governorate_id: 2,
    },
    {
      id: 3,
      name: "AutoPro",
      coordinates: "41.878113,-87.629799",
      description: "Top-notch car maintenance and repair.",
      owner_id: 1,
      governorate_id: 3,
    },
    {
      id: 4,
      name: "HomeClean",
      coordinates: "29.760427,-95.369804",
      description: "Expert home cleaning services.",
      owner_id: 1,
      governorate_id: 4,
    },
    {
      id: 5,
      name: "FitLife",
      coordinates: "33.448376,-112.074036",
      description: "Personalized fitness and wellness programs.",
      owner_id: 1,
      governorate_id: 5,
    },
    {
      id: 6,
      name: "Gadget World",
      coordinates: "39.739236,-104.990251",
      description: "Latest gadgets and tech accessories.",
      owner_id: 1,
      governorate_id: 6,
    },
    {
      id: 7,
      name: "GardenPro",
      coordinates: "37.774929,-122.419418",
      description: "Professional gardening and landscaping services.",
      owner_id: 1,
      governorate_id: 7,
    },
    {
      id: 8,
      name: "CookMaster",
      coordinates: "47.606209,-122.332069",
      description: "Professional cooking classes and catering services.",
      owner_id: 1,
      governorate_id: 8,
    },
    {
      id: 9,
      name: "PetCare",
      coordinates: "32.715736,-117.161087",
      description: "Comprehensive pet care services.",
      owner_id: 1,
      governorate_id: 9,
    },
    {
      id: 10,
      name: "HandyMan",
      coordinates: "29.424349,-98.491142",
      description: "Reliable handyman services for your home.",
      owner_id: 1,
      governorate_id: 10,
    },
    {
      id: 11,
      name: "Tech Solutions",
      coordinates: "35.689487,139.691711",
      description: "Expert tech support and solutions.",

      owner_id: 1,
      governorate_id: 11,
    },
    {
      id: 12,
      name: "HealthHub",
      coordinates: "48.856613,2.352222",
      description: "Comprehensive health and wellness services.",
      owner_id: 1,
      governorate_id: 12,
    },
    {
      id: 13,
      name: "AutoCare",
      coordinates: "51.507351,-0.127758",
      description: "Professional auto care and maintenance services.",
      owner_id: 1,
      governorate_id: 13,
    },
    {
      id: 14,
      name: "SparkleClean",
      coordinates: "52.520008,13.404954",
      description: "Professional cleaning services for your home and office.",
      owner_id: 1,
      governorate_id: 14,
    },
    {
      id: 15,
      name: "Fitness Zone",
      coordinates: "40.712776,-74.005974",
      description: "State-of-the-art fitness and wellness center.",
      owner_id: 1,
      governorate_id: 15,
    },
    {
      id: 16,
      name: "GadgetFix",
      coordinates: "34.052235,-118.243683",
      description: "Reliable gadget repair services.",
      owner_id: 1,
      governorate_id: 16,
    },
    {
      id: 17,
      name: "HomeFix",
      coordinates: "41.878113,-87.629799",
      description: "Expert home improvement services.",
      owner_id: 1,
      governorate_id: 17,
    },
    {
      id: 18,
      name: "PetGroomers",
      coordinates: "29.760427,-95.369804",
      description: "Top-notch pet grooming services.",
      owner_id: 1,
      governorate_id: 18,
    },
    {
      id: 19,
      name: "TechMasters",
      coordinates: "33.448376,-112.074036",
      description: "Professional tech repair and support services.",
      owner_id: 1,
      governorate_id: 19,
    },
    {
      id: 20,
      name: "Beauty Haven",
      coordinates: "39.739236,-104.990251",
      description: "Luxurious beauty and spa services.",
      owner_id: 1,
      governorate_id: 20,
    },
    {
      id: 21,
      name: "AutoExperts",
      coordinates: "37.774929,-122.419418",
      description: "Expert auto repair and maintenance services.",
      owner_id: 1,
      governorate_id: 21,
    },
    {
      id: 22,
      name: "Garden Experts",
      coordinates: "47.606209,-122.332069",
      description: "Professional gardening and landscaping services.",
      owner_id: 1,
      governorate_id: 22,
    },
    {
      id: 23,
      name: "CookMaster Pro",
      coordinates: "32.715736,-117.161087",
      description: "Professional cooking classes and catering services.",
      owner_id: 1,
      governorate_id: 23,
    },
    {
      id: 24,
      name: "Pet Paradise",
      coordinates: "29.424349,-98.491142",
      description: "Comprehensive pet care services.",
      owner_id: 1,
      governorate_id: 24,
    },
    {
      id: 25,
      name: "Handy Experts",
      coordinates: "35.689487,139.691711",
      description: "Expert handyman services for your home.",
      owner_id: 1,
      governorate_id: 1,
    },
  ],
  services: [
    {
      id: 1,
      name: "Laptop Repair",
      description: "Professional laptop repair services.",
      price: 100.0,
      store_id: 1,
      category_id: 801,
    },
    {
      id: 2,
      name: "Phone Screen Replacement",
      description: "Fast phone screen replacement.",
      price: 50.0,
      store_id: 1,
      category_id: 801,
    },
    {
      id: 3,
      name: "Facial Treatment",
      description: "Relaxing and rejuvenating facial treatments.",
      price: 70.0,
      store_id: 2,
      category_id: 203,
    },
    {
      id: 4,
      name: "Manicure",
      description: "Professional manicure services.",
      price: 30.0,
      store_id: 2,
      category_id: 203,
    },
    {
      id: 5,
      name: "Oil Change",
      description: "Quick and efficient oil change service.",
      price: 40.0,
      store_id: 3,
      category_id: 502,
    },
    {
      id: 6,
      name: "Tire Rotation",
      description: "Professional tire rotation service.",
      price: 20.0,
      store_id: 3,
      category_id: 503,
    },
    {
      id: 7,
      name: "Deep Cleaning",
      description: "Thorough and comprehensive home cleaning.",
      price: 150.0,
      store_id: 4,
      category_id: 101,
    },
    {
      id: 8,
      name: "Window Cleaning",
      description: "Spotless window cleaning service.",
      price: 60.0,
      store_id: 4,
      category_id: 101,
    },
    {
      id: 9,
      name: "Personal Training",
      description: "One-on-one personal training sessions.",
      price: 80.0,
      store_id: 5,
      category_id: 202,
    },
    {
      id: 10,
      name: "Yoga Classes",
      description: "Group and individual yoga classes.",
      price: 50.0,
      store_id: 5,
      category_id: 202,
    },
    {
      id: 11,
      name: "Gadget Setup",
      description: "Professional gadget setup and installation.",
      price: 60.0,
      store_id: 6,
      category_id: 801,
    },
    {
      id: 12,
      name: "Tech Support",
      description: "24/7 tech support for all your gadgets.",
      price: 100.0,
      store_id: 6,
      category_id: 801,
    },
    {
      id: 13,
      name: "Lawn Mowing",
      description: "Efficient and reliable lawn mowing service.",
      price: 50.0,
      store_id: 7,
      category_id: 103,
    },
    {
      id: 14,
      name: "Garden Design",
      description: "Custom garden design and landscaping.",
      price: 200.0,
      store_id: 7,
      category_id: 103,
    },
    {
      id: 15,
      name: "Cooking Classes",
      description: "Hands-on cooking classes for all skill levels.",
      price: 75.0,
      store_id: 8,
      category_id: 1001,
    },
    {
      id: 16,
      name: "Event Catering",
      description: "Full-service catering for events.",
      price: 500.0,
      store_id: 8,
      category_id: 702,
    },
    {
      id: 17,
      name: "Pet Grooming",
      description: "Full grooming services for pets.",
      price: 40.0,
      store_id: 9,
      category_id: 403,
    },
    {
      id: 18,
      name: "Pet Boarding",
      description: "Safe and comfortable pet boarding.",
      price: 30.0,
      store_id: 9,
      category_id: 401,
    },
    {
      id: 19,
      name: "Furniture Assembly",
      description: "Quick and efficient furniture assembly.",
      price: 60.0,
      store_id: 10,
      category_id: 102,
    },
    {
      id: 20,
      name: "Home Repairs",
      description: "Professional home repair services.",
      price: 100.0,
      store_id: 10,
      category_id: 102,
    },
    {
      id: 21,
      name: "Software Installation",
      description: "Professional software installation services.",
      price: 50.0,
      store_id: 11,
      category_id: 801,
    },
    {
      id: 22,
      name: "System Optimization",
      description: "Optimize your system for better performance.",
      price: 75.0,
      store_id: 11,
      category_id: 801,
    },
    {
      id: 23,
      name: "Nutritional Counseling",
      description: "Personalized nutritional counseling services.",
      price: 100.0,
      store_id: 12,
      category_id: 202,
    },
    {
      id: 24,
      name: "Massage Therapy",
      description: "Relaxing and therapeutic massage services.",
      price: 80.0,
      store_id: 12,
      category_id: 203,
    },
    {
      id: 25,
      name: "Brake Service",
      description: "Comprehensive brake inspection and repair.",
      price: 120.0,
      store_id: 13,
      category_id: 502,
    },
    {
      id: 26,
      name: "Engine Tune-Up",
      description: "Optimize your engine performance.",
      price: 150.0,
      store_id: 13,
      category_id: 502,
    },
    {
      id: 27,
      name: "Carpet Cleaning",
      description: "Deep cleaning for your carpets.",
      price: 80.0,
      store_id: 14,
      category_id: 101,
    },
    {
      id: 28,
      name: "Office Cleaning",
      description: "Regular cleaning services for your office.",
      price: 100.0,
      store_id: 14,
      category_id: 101,
    },
    {
      id: 29,
      name: "Personal Training",
      description: "Personalized fitness training sessions.",
      price: 90.0,
      store_id: 15,
      category_id: 202,
    },
    {
      id: 30,
      name: "Group Fitness Classes",
      description: "Fun and engaging group fitness classes.",
      price: 40.0,
      store_id: 15,
      category_id: 202,
    },
    {
      id: 31,
      name: "Phone Repair",
      description: "Quick and efficient phone repair services.",
      price: 50.0,
      store_id: 16,
      category_id: 801,
    },
    {
      id: 32,
      name: "Tablet Repair",
      description: "Professional tablet repair services.",
      price: 60.0,
      store_id: 16,
      category_id: 801,
    },
    {
      id: 33,
      name: "Plumbing Services",
      description: "Reliable plumbing services for your home.",
      price: 100.0,
      store_id: 17,
      category_id: 102,
    },
    {
      id: 34,
      name: "Electrical Services",
      description: "Professional electrical services for your home.",
      price: 120.0,
      store_id: 17,
      category_id: 102,
    },
    {
      id: 35,
      name: "Full Grooming",
      description: "Comprehensive grooming services for pets.",
      price: 50.0,
      store_id: 18,
      category_id: 403,
    },
    {
      id: 36,
      name: "Nail Trimming",
      description: "Professional nail trimming for pets.",
      price: 20.0,
      store_id: 18,
      category_id: 403,
    },
    {
      id: 37,
      name: "Computer Repair",
      description: "Expert computer repair services.",
      price: 70.0,
      store_id: 19,
      category_id: 801,
    },
    {
      id: 38,
      name: "Network Setup",
      description: "Professional network setup and troubleshooting.",
      price: 100.0,
      store_id: 19,
      category_id: 801,
    },
    {
      id: 39,
      name: "Hair Styling",
      description: "Professional hair styling services.",
      price: 60.0,
      store_id: 20,
      category_id: 203,
    },
    {
      id: 40,
      name: "Spa Treatments",
      description: "Relaxing and rejuvenating spa treatments.",
      price: 100.0,
      store_id: 20,
      category_id: 203,
    },
    {
      id: 41,
      name: "Transmission Repair",
      description: "Professional transmission repair services.",
      price: 200.0,
      store_id: 21,
      category_id: 502,
    },
    {
      id: 42,
      name: "Battery Replacement",
      description: "Quick and reliable battery replacement.",
      price: 80.0,
      store_id: 21,
      category_id: 503,
    },
    {
      id: 43,
      name: "Window Cleaning",
      description: "Expert window cleaning services for your home.",
      price: 70.0,
      store_id: 22,
      category_id: 101,
    },
    {
      id: 44,
      name: "Pressure Washing",
      description: "Thorough pressure washing for your home exterior.",
      price: 150.0,
      store_id: 22,
      category_id: 101,
    },
    {
      id: 45,
      name: "Yoga Instruction",
      description: "Personalized yoga instruction for all levels.",
      price: 60.0,
      store_id: 23,
      category_id: 202,
    },
    {
      id: 46,
      name: "Meditation Classes",
      description: "Group and individual meditation classes.",
      price: 40.0,
      store_id: 23,
      category_id: 202,
    },
    {
      id: 47,
      name: "Data Recovery",
      description: "Professional data recovery services.",
      price: 200.0,
      store_id: 24,
      category_id: 801,
    },
    {
      id: 48,
      name: "Cybersecurity Consultation",
      description: "Expert cybersecurity consultation services.",
      price: 300.0,
      store_id: 24,
      category_id: 801,
    },
    {
      id: 49,
      name: "Interior Design",
      description: "Custom interior design services for your home.",
      price: 500.0,
      store_id: 25,
      category_id: 102,
    },
    {
      id: 50,
      name: "Furniture Restoration",
      description: "Professional furniture restoration services.",
      price: 200.0,
      store_id: 25,
      category_id: 102,
    },
  ],
  reviews: [
    {
      message: "Excellent service!",
      picture: null,
      rating: 4.5,
      quality: 4.7,
      fees: 4.0,
      punctuality: 4.8,
      politeness: 4.6,
      user_id: 2,
      reviewee_id: 3,
    },
    {
      message: "Very satisfied with the work.",
      picture: null,
      rating: 4.8,
      quality: 4.9,
      fees: 4.7,
      punctuality: 4.8,
      politeness: 4.8,
      user_id: 2,
      reviewee_id: 3,
    },
    {
      message: "Good job but a bit late.",
      picture: null,
      rating: 3.8,
      quality: 4.0,
      fees: 3.5,
      punctuality: 3.2,
      politeness: 4.0,
      user_id: 2,
      reviewee_id: 3,
    },
    {
      message: "The quality was not as expected.",
      picture: null,
      rating: 2.5,
      quality: 2.0,
      fees: 3.0,
      punctuality: 3.5,
      politeness: 2.0,
      user_id: 3,
      reviewee_id: 2,
    },
    {
      message: "Highly recommend!",
      picture: null,
      rating: 5.0,
      quality: 5.0,
      fees: 5.0,
      punctuality: 5.0,
      politeness: 5.0,
      user_id: 2,
      reviewee_id: 3,
    },
    {
      message: "Could be better.",
      picture: null,
      rating: 3.0,
      quality: 3.5,
      fees: 2.5,
      punctuality: 3.0,
      politeness: 3.0,
      user_id: 3,
      reviewee_id: 2,
    },
    {
      message: "Very professional.",
      picture: null,
      rating: 4.7,
      quality: 4.5,
      fees: 4.8,
      punctuality: 4.6,
      politeness: 4.9,
      user_id: 1,
      reviewee_id: 2,
    },
    {
      message: "Average experience.",
      picture: null,
      rating: 3.5,
      quality: 3.5,
      fees: 3.5,
      punctuality: 3.5,
      politeness: 3.5,
      user_id: 1,
      reviewee_id: 3,
    },
    {
      message: "Excellent communication.",
      picture: null,
      rating: 4.8,
      quality: 4.9,
      fees: 4.7,
      punctuality: 4.9,
      politeness: 4.8,
      user_id: 1,
      reviewee_id: 2,
    },
    {
      message: "Not happy with the result.",
      picture: null,
      rating: 2.0,
      quality: 2.0,
      fees: 2.5,
      punctuality: 2.0,
      politeness: 2.0,
      user_id: 1,
      reviewee_id: 3,
    },
    {
      message: "Service was okay.",
      picture: null,
      rating: 3.0,
      quality: 3.0,
      fees: 3.0,
      punctuality: 3.0,
      politeness: 3.0,
      user_id: 1,
      reviewee_id: 2,
    },
    {
      message: "Really impressed!",
      picture: null,
      rating: 5.0,
      quality: 5.0,
      fees: 5.0,
      punctuality: 5.0,
      politeness: 5.0,
      user_id: 1,
      reviewee_id: 3,
    },
    {
      message: "The provider was late.",
      picture: null,
      rating: 3.2,
      quality: 3.5,
      fees: 3.0,
      punctuality: 2.5,
      politeness: 3.5,
      user_id: 1,
      reviewee_id: 2,
    },
    {
      message: "Great value for money.",
      picture: null,
      rating: 4.5,
      quality: 4.6,
      fees: 4.7,
      punctuality: 4.4,
      politeness: 4.5,
      user_id: 1,
      reviewee_id: 3,
    },
    {
      message: "Very courteous.",
      picture: null,
      rating: 4.8,
      quality: 4.8,
      fees: 4.8,
      punctuality: 4.8,
      politeness: 5.0,
      user_id: 1,
      reviewee_id: 3,
    },
    {
      message: "Will use again.",
      picture: null,
      rating: 4.5,
      quality: 4.5,
      fees: 4.5,
      punctuality: 4.5,
      politeness: 4.5,
      user_id: 1,
      reviewee_id: 2,
    },
    {
      message: "Not satisfied with the fees.",
      picture: null,
      rating: 2.5,
      quality: 3.0,
      fees: 2.0,
      punctuality: 3.0,
      politeness: 2.5,
      user_id: 1,
      reviewee_id: 3,
    },
    {
      message: "Very punctual.",
      picture: null,
      rating: 4.6,
      quality: 4.7,
      fees: 4.5,
      punctuality: 4.8,
      politeness: 4.5,
      user_id: 1,
      reviewee_id: 2,
    },
    {
      message: "Good overall experience.",
      picture: null,
      rating: 4.2,
      quality: 4.3,
      fees: 4.0,
      punctuality: 4.0,
      politeness: 4.5,
      user_id: 1,
      reviewee_id: 3,
    },
    {
      message: "The quality was poor.",
      picture: null,
      rating: 1.5,
      quality: 1.0,
      fees: 2.0,
      punctuality: 1.5,
      politeness: 1.5,
      user_id: 1,
      reviewee_id: 2,
    },
    {
      message: "Everything was perfect!",
      picture: null,
      rating: 5.0,
      quality: 5.0,
      fees: 5.0,
      punctuality: 5.0,
      politeness: 5.0,
      user_id: 1,
      reviewee_id: 3,
    },
    {
      message: "Not worth the price.",
      picture: null,
      rating: 2.0,
      quality: 2.5,
      fees: 2.0,
      punctuality: 2.0,
      politeness: 2.5,
      user_id: 3,
      reviewee_id: 2,
    },
    {
      message: "Prompt service.",
      picture: null,
      rating: 4.7,
      quality: 4.8,
      fees: 4.6,
      punctuality: 4.8,
      politeness: 4.7,
      user_id: 2,
      reviewee_id: 3,
    },
    {
      message: "Overall good experience.",
      picture: null,
      rating: 4.3,
      quality: 4.4,
      fees: 4.0,
      punctuality: 4.2,
      politeness: 4.3,
      user_id: 3,
      reviewee_id: 2,
    },
    {
      message: "The service was average.",
      picture: null,
      rating: 3.0,
      quality: 3.0,
      fees: 3.0,
      punctuality: 3.0,
      politeness: 3.0,
      user_id: 2,
      reviewee_id: 3,
    },
    {
      message: "Great customer support.",
      picture: null,
      rating: 4.9,
      quality: 4.8,
      fees: 4.7,
      punctuality: 4.9,
      politeness: 5.0,
      user_id: 2,
      reviewee_id: 3,
    },
    {
      message: "Service was decent.",
      picture: null,
      rating: 3.5,
      quality: 3.5,
      fees: 3.5,
      punctuality: 3.5,
      politeness: 3.5,
      user_id: 3,
      reviewee_id: 2,
    },
    {
      message: "Very professional and friendly.",
      picture: null,
      rating: 4.8,
      quality: 4.9,
      fees: 4.7,
      punctuality: 4.8,
      politeness: 4.9,
      user_id: 2,
      reviewee_id: 3,
    },
    {
      message: "Did not meet expectations.",
      picture: null,
      rating: 2.5,
      quality: 2.0,
      fees: 3.0,
      punctuality: 2.5,
      politeness: 2.5,
      user_id: 3,
      reviewee_id: 2,
    },
    {
      message: "Excellent service and support.",
      picture: null,
      rating: 5.0,
      quality: 5.0,
      fees: 5.0,
      punctuality: 5.0,
      politeness: 5.0,
      user_id: 2,
      reviewee_id: 3,
    },
    {
      message: "The quality was inconsistent.",
      picture: null,
      rating: 3.0,
      quality: 3.0,
      fees: 3.0,
      punctuality: 3.0,
      politeness: 3.0,
      user_id: 3,
      reviewee_id: 2,
    },
    {
      message: "Good service but could improve.",
      picture: null,
      rating: 3.7,
      quality: 3.8,
      fees: 3.5,
      punctuality: 3.6,
      politeness: 3.8,
      user_id: 2,
      reviewee_id: 3,
    },
    {
      message: "Very reliable service.",
      picture: null,
      rating: 4.6,
      quality: 4.7,
      fees: 4.5,
      punctuality: 4.6,
      politeness: 4.6,
      user_id: 3,
      reviewee_id: 2,
    },
    {
      message: "Average, nothing special.",
      picture: null,
      rating: 3.2,
      quality: 3.0,
      fees: 3.5,
      punctuality: 3.0,
      politeness: 3.5,
      user_id: 2,
      reviewee_id: 3,
    },
    {
      message: "Outstanding service.",
      picture: null,
      rating: 4.9,
      quality: 4.8,
      fees: 4.7,
      punctuality: 5.0,
      politeness: 4.9,
      user_id: 3,
      reviewee_id: 2,
    },
    {
      message: "Will definitely use again.",
      picture: null,
      rating: 4.8,
      quality: 4.8,
      fees: 4.8,
      punctuality: 4.8,
      politeness: 4.8,
      user_id: 2,
      reviewee_id: 3,
    },
    {
      message: "Service was below average.",
      picture: null,
      rating: 2.8,
      quality: 2.5,
      fees: 2.5,
      punctuality: 3.0,
      politeness: 2.5,
      user_id: 3,
      reviewee_id: 2,
    },
    {
      message: "Very good experience overall.",
      picture: null,
      rating: 4.5,
      quality: 4.6,
      fees: 4.5,
      punctuality: 4.5,
      politeness: 4.5,
      user_id: 2,
      reviewee_id: 3,
    },
    {
      message: "Quality was as expected.",
      picture: null,
      rating: 4.0,
      quality: 4.0,
      fees: 4.0,
      punctuality: 4.0,
      politeness: 4.0,
      user_id: 3,
      reviewee_id: 2,
    },
    {
      message: "Could use some improvements.",
      picture: null,
      rating: 3.3,
      quality: 3.5,
      fees: 3.0,
      punctuality: 3.0,
      politeness: 3.5,
      user_id: 2,
      reviewee_id: 3,
    },
    {
      message: "Service was excellent!",
      picture: null,
      rating: 4.9,
      quality: 5.0,
      fees: 4.8,
      punctuality: 4.9,
      politeness: 5.0,
      user_id: 3,
      reviewee_id: 2,
    },
    {
      message: "Not up to the mark.",
      picture: null,
      rating: 2.7,
      quality: 2.5,
      fees: 2.8,
      punctuality: 2.7,
      politeness: 2.7,
      user_id: 2,
      reviewee_id: 3,
    },
    {
      message: "Fantastic job!",
      picture: null,
      rating: 4.8,
      quality: 4.8,
      fees: 4.8,
      punctuality: 4.8,
      politeness: 4.8,
      user_id: 3,
      reviewee_id: 2,
    },
    {
      message: "Mediocre service.",
      picture: null,
      rating: 3.1,
      quality: 3.0,
      fees: 3.2,
      punctuality: 3.0,
      politeness: 3.2,
      user_id: 2,
      reviewee_id: 3,
    },
    {
      message: "Excellent performance.",
      picture: null,
      rating: 4.7,
      quality: 4.8,
      fees: 4.6,
      punctuality: 4.8,
      politeness: 4.7,
      user_id: 3,
      reviewee_id: 2,
    },
    {
      message: "Not bad, but room for improvement.",
      picture: null,
      rating: 3.6,
      quality: 3.5,
      fees: 3.5,
      punctuality: 3.6,
      politeness: 3.6,
      user_id: 2,
      reviewee_id: 3,
    },
    {
      message: "Perfect service.",
      picture: null,
      rating: 5.0,
      quality: 5.0,
      fees: 5.0,
      punctuality: 5.0,
      politeness: 5.0,
      user_id: 3,
      reviewee_id: 2,
    },
    {
      message: "Service did not meet expectations.",
      picture: null,
      rating: 2.8,
      quality: 2.5,
      fees: 2.5,
      punctuality: 2.8,
      politeness: 2.8,
      user_id: 2,
      reviewee_id: 3,
    },
    {
      message: "Very happy with the service.",
      picture: null,
      rating: 4.7,
      quality: 4.8,
      fees: 4.6,
      punctuality: 4.7,
      politeness: 4.7,
      user_id: 3,
      reviewee_id: 2,
    },
    {
      message: "Service was acceptable.",
      picture: null,
      rating: 3.4,
      quality: 3.5,
      fees: 3.0,
      punctuality: 3.5,
      politeness: 3.5,
      user_id: 2,
      reviewee_id: 3,
    },
    {
      message: "Great experience overall.",
      picture: null,
      rating: 4.5,
      quality: 4.6,
      fees: 4.5,
      punctuality: 4.5,
      politeness: 4.5,
      user_id: 3,
      reviewee_id: 2,
    },
    {
      message: "Quality was lacking.",
      picture: null,
      rating: 2.5,
      quality: 2.5,
      fees: 2.5,
      punctuality: 2.5,
      politeness: 2.5,
      user_id: 2,
      reviewee_id: 3,
    },
    {
      message: "Impressive work!",
      picture: null,
      rating: 4.9,
      quality: 5.0,
      fees: 4.8,
      punctuality: 4.9,
      politeness: 4.9,
      user_id: 3,
      reviewee_id: 2,
    },
    {
      message: "Satisfactory service.",
      picture: null,
      rating: 3.7,
      quality: 3.8,
      fees: 3.5,
      punctuality: 3.7,
      politeness: 3.7,
      user_id: 2,
      reviewee_id: 3,
    },
    {
      message: "Wonderful experience.",
      picture: null,
      rating: 4.8,
      quality: 4.9,
      fees: 4.7,
      punctuality: 4.8,
      politeness: 4.8,
      user_id: 3,
      reviewee_id: 2,
    },
    {
      message: "Not up to the standard.",
      picture: null,
      rating: 2.9,
      quality: 2.8,
      fees: 2.8,
      punctuality: 2.9,
      politeness: 2.9,
      user_id: 2,
      reviewee_id: 3,
    },
    {
      message: "Highly recommended!",
      picture: null,
      rating: 4.8,
      quality: 4.9,
      fees: 4.7,
      punctuality: 4.8,
      politeness: 4.8,
      user_id: 3,
      reviewee_id: 2,
    },
  ],
};

const prefixPatterns = [
  // Europe
  { prefix: "+44", pattern: /^\+44\d{10}$/ }, // United Kingdom
  { prefix: "+33", pattern: /^\+33\d{9}$/ }, // France
  { prefix: "+49", pattern: /^\+49\d{10}$/ }, // Germany
  { prefix: "+39", pattern: /^\+39\d{10}$/ }, // Italy
  { prefix: "+31", pattern: /^\+31\d{9,10}$/ }, // Netherlands
  { prefix: "+34", pattern: /^\+34\d{9}$/ }, // Spain
  { prefix: "+41", pattern: /^\+41\d{9}$/ }, // Switzerland
  { prefix: "+46", pattern: /^\+46\d{9}$/ }, // Sweden
  { prefix: "+358", pattern: /^\+358\d{9}$/ }, // Finland
  { prefix: "+47", pattern: /^\+47\d{8}$/ }, // Norway

  // North Africa
  { prefix: "+213", pattern: /^\+213\d{9}$/ }, // Algeria
  { prefix: "+20", pattern: /^\+20\d{10}$/ }, // Egypt
  { prefix: "+212", pattern: /^\+212\d{9}$/ }, // Morocco
  { prefix: "+216", pattern: /^\+216\d{8}$/ }, // Tunisia
  { prefix: "+218", pattern: /^\+218\d{9}$/ }, // Libya
  { prefix: "+235", pattern: /^\+235\d{8}$/ }, // Chad
  { prefix: "+249", pattern: /^\+249\d{9}$/ }, // Sudan
  { prefix: "+212", pattern: /^\+212\d{9}$/ }, // Western Sahara
  { prefix: "+213", pattern: /^\+213\d{9}$/ }, // Canary Islands
  { prefix: "+20", pattern: /^\+20\d{10}$/ }, // Canary Islands

  // USA
  { prefix: "+1", pattern: /^\+1\d{10}$/ }, // United States
  { prefix: "+1", pattern: /^\+1\d{10}$/ }, // Canada
  { prefix: "+52", pattern: /^\+52\d{10}$/ }, // Mexico
  { prefix: "+52", pattern: /^\+52\d{10}$/ }, // Belize
  { prefix: "+52", pattern: /^\+52\d{10}$/ }, // Guatemala
  { prefix: "+52", pattern: /^\+52\d{10}$/ }, // Honduras
  { prefix: "+52", pattern: /^\+52\d{10}$/ }, // El Salvador
  { prefix: "+52", pattern: /^\+52\d{10}$/ }, // Nicaragua
  { prefix: "+52", pattern: /^\+52\d{10}$/ }, // Costa Rica
  { prefix: "+52", pattern: /^\+52\d{10}$/ }, // Panama
];

const getOneMinuteBeforeMidnight = () => {
  const now = new Date();
  const endOfDay = new Date(
    now.getFullYear(),
    now.getMonth(),
    now.getDate(),
    23,
    59,
    0,
    0
  );
  return endOfDay;
};

module.exports = {
  constantId,
  prefixPatterns,
  getOneMinuteBeforeMidnight,
};
