// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbjlbasCkxL7mTbvuOTcik0NGPu4qIjWc',
    appId: '1:141879224852:web:dbcda18351387bf49dd501',
    messagingSenderId: '141879224852',
    projectId: 'dootify-8a5df',
    authDomain: 'dootify-8a5df.firebaseapp.com',
    storageBucket: 'dootify-8a5df.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8M1hW23j6ccXYCfPk_atf527pVTyNGus',
    appId: '1:141879224852:android:b8f3b81e5f0800dd9dd501',
    messagingSenderId: '141879224852',
    projectId: 'dootify-8a5df',
    storageBucket: 'dootify-8a5df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP1qsP5zYXO5m2Pp0-oFmnUQz6EwfbiMQ',
    appId: '1:141879224852:ios:6457574ea6638ce69dd501',
    messagingSenderId: '141879224852',
    projectId: 'dootify-8a5df',
    storageBucket: 'dootify-8a5df.firebasestorage.app',
    iosClientId: '141879224852-2vtnig76hskv3blpojtc1buu53g0j05e.apps.googleusercontent.com',
    iosBundleId: 'com.nextGenEase.dootify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP1qsP5zYXO5m2Pp0-oFmnUQz6EwfbiMQ',
    appId: '1:141879224852:ios:6457574ea6638ce69dd501',
    messagingSenderId: '141879224852',
    projectId: 'dootify-8a5df',
    storageBucket: 'dootify-8a5df.firebasestorage.app',
    iosClientId: '141879224852-2vtnig76hskv3blpojtc1buu53g0j05e.apps.googleusercontent.com',
    iosBundleId: 'com.nextGenEase.dootify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbjlbasCkxL7mTbvuOTcik0NGPu4qIjWc',
    appId: '1:141879224852:web:3cf195ff6bd1a1bd9dd501',
    messagingSenderId: '141879224852',
    projectId: 'dootify-8a5df',
    authDomain: 'dootify-8a5df.firebaseapp.com',
    storageBucket: 'dootify-8a5df.firebasestorage.app',
  );

}