// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbjlbasCkxL7mTbvuOTcik0NGPu4qIjWc',
    appId: '1:141879224852:web:df7652ced0419dfd9dd501',
    messagingSenderId: '141879224852',
    projectId: 'dootify-8a5df',
    authDomain: 'dootify-8a5df.firebaseapp.com',
    storageBucket: 'dootify-8a5df.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8M1hW23j6ccXYCfPk_atf527pVTyNGus',
    appId: '1:141879224852:android:769466f7d634060b9dd501',
    messagingSenderId: '141879224852',
    projectId: 'dootify-8a5df',
    storageBucket: 'dootify-8a5df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP1qsP5zYXO5m2Pp0-oFmnUQz6EwfbiMQ',
    appId: '1:141879224852:ios:beb1b74a96b0a72d9dd501',
    messagingSenderId: '141879224852',
    projectId: 'dootify-8a5df',
    storageBucket: 'dootify-8a5df.firebasestorage.app',
    iosClientId: '141879224852-5ub8n04hki2of5nmrjoi2ttkll17pc95.apps.googleusercontent.com',
    iosBundleId: 'com.sparkedgesolutions.dootify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP1qsP5zYXO5m2Pp0-oFmnUQz6EwfbiMQ',
    appId: '1:141879224852:ios:beb1b74a96b0a72d9dd501',
    messagingSenderId: '141879224852',
    projectId: 'dootify-8a5df',
    storageBucket: 'dootify-8a5df.firebasestorage.app',
    iosClientId: '141879224852-5ub8n04hki2of5nmrjoi2ttkll17pc95.apps.googleusercontent.com',
    iosBundleId: 'com.sparkedgesolutions.dootify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbjlbasCkxL7mTbvuOTcik0NGPu4qIjWc',
    appId: '1:141879224852:web:6aadbeb516b57a789dd501',
    messagingSenderId: '141879224852',
    projectId: 'dootify-8a5df',
    authDomain: 'dootify-8a5df.firebaseapp.com',
    storageBucket: 'dootify-8a5df.firebasestorage.app',
  );

}