// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9slCSaKS-EVPjSKa772HZpmEonxt1x9s',
    appId: '1:786248351245:web:ff8589f04404779dbcdf44',
    messagingSenderId: '786248351245',
    projectId: 'side-hustle-dc63b',
    authDomain: 'side-hustle-dc63b.firebaseapp.com',
    storageBucket: 'side-hustle-dc63b.appspot.com',
    measurementId: 'G-KCXWET3G2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvvIdN067XLWb8TnJFlIhxhvBUJaf-XiU',
    appId: '1:786248351245:android:126f6f04e44392d3bcdf44',
    messagingSenderId: '786248351245',
    projectId: 'side-hustle-dc63b',
    storageBucket: 'side-hustle-dc63b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0In5EV30h2dR3l4KPRVeRyMExecVH8y8',
    appId: '1:786248351245:ios:45ad54b9065aa11ebcdf44',
    messagingSenderId: '786248351245',
    projectId: 'side-hustle-dc63b',
    storageBucket: 'side-hustle-dc63b.appspot.com',
    iosBundleId: 'com.example.sideHustle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0In5EV30h2dR3l4KPRVeRyMExecVH8y8',
    appId: '1:786248351245:ios:45ad54b9065aa11ebcdf44',
    messagingSenderId: '786248351245',
    projectId: 'side-hustle-dc63b',
    storageBucket: 'side-hustle-dc63b.appspot.com',
    iosBundleId: 'com.example.sideHustle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9slCSaKS-EVPjSKa772HZpmEonxt1x9s',
    appId: '1:786248351245:web:fc1424d5d403bf9ebcdf44',
    messagingSenderId: '786248351245',
    projectId: 'side-hustle-dc63b',
    authDomain: 'side-hustle-dc63b.firebaseapp.com',
    storageBucket: 'side-hustle-dc63b.appspot.com',
    measurementId: 'G-7WQHPB21RR',
  );
}
